// Copyright TagMan Ltd 2013: T 3.00 V tags/tm-3.3.3 C Thu Nov 28 10:12:15 2013
//
// Copyright © 2012 TagMan. All rights reserved. V tags/tm-3.3.3 R 12036 C 2012-08-07 14:30:58
(function(j,p){function n(a,d,e){if(arguments.length<2){b.util.log("`account` and `id` arguments are required","error");for(var f in this)delete this[f]}else{for(var g in e)typeof b.conf[g]=="undefined"&&b.util.log("Invalid property passed to Container constructor: "+g,"warning");e=e||{};this.param=e.param||{};this.account=a;this.id=this.baseId=d;this.tags=[];this._setOptions(e);this.host=this.host.replace(/^(?:https?:)?\/\//i,"");this.log=new b.Log(b.logOptions||e.log);this.log.container=this;if(e.tags){if(e.tags instanceof
b.Tag)e.tags=[e.tags];this.addTags.apply(this,e.tags)}(this.debugMode=e.debugMode||false)&&this.log.setDebugMode();e.statRate&&this.log.setStatTypeRate("container",e.statRate);if(!e.waitTest)b.waitLatency=b.POLL_INTERVAL;this.blockCalls=0}}function r(){b.doTags(b.position.WINDOW_LOADED);var a=(new Date).getTime(),d=function(){for(var f=b._containers,g=0,h=f.length;g<h;g++){var i=f[g];if(!i.isLandingPageDisabled()&&!i.isTimedOut()){i=i.tags;for(var k=0,o=i.length;k<o;k++){var q=i[k];if(!q.hasExecuted()&&
q.position<=b.position.WINDOW_LOADED)return true}}}return false};if(d())var e=j.setInterval(function(){b.util.log("Timer calling doTags(DOTAGS_TIMER)...","debug");b.doTags(b.position.DOTAGS_TIMER);var f=(new Date).getTime()-a>3E4,g=d();if(f||!g){b.util.log("No more tags need servicing ("+!g+") or timed out ("+f+"), cancelling dotags timer","debug");j.clearInterval(e)}},1E4)}var B=function(){return true},s=j.document;s.head||s.getElementsByTagName("head");var C,b=j.TMAN||(j.TMAN={});b.startTime||(b.startTime=
new Date);b.blockingTime=0;b.currentPosition=0;b.syncSafe=false;b._secure=location.protocol=="https:";b.MAX_BLOCK_CALLS=400;b.getPageLoadTime=function(){return new Date-b.startTime};b.waitTest||(b.waitTest=false);b.account={};b.POLL_INTERVAL=b.POLL_INTERVAL||100;b.MAX_COOKIE_LENGTH=4E3;b._doTagsCallback=false;if(!b.util)b.util={elements:0,K:function(a){return a},extend:function(a,d){for(var e in d)a[e]=d[e];return a},isInIframe:function(){return j.top!=j?1:0},isArray:function(){return typeof Array.isArray===
"undefined"?function(a){return Object.prototype.toString.call(a)==="[object Array]"}:Array.isArray}(),findById:function(a){if(!a)return null;b.util.isArray(a)||(a=[a]);for(var d=0,e=a.length;d<e;d++)if(a[d]){var f=s.getElementById(a[d]);if(f)return f}return null},createImage:function(a){return(new Image).src=a},append:function(a,d){if(!a.id)a.id="tmap_"+b.util.elements++;if(d){if(!d.noOnload){var e=b.load.onLoad;if("onreadystatechange"in a)a.onreadystatechange=function(){if(a.readyState==="complete"||
a.readyState==="loaded"){a.onload=a.onerror=a.onreadystatechange=null;e.call(a,true)}};a.onload=function(){e.call(a,true)};a.onerror=function(){e.call(a,false)};d.url||(d.url=a.src||a.data);d.id||(d.id=a.id);a.tagman={};a.tagman.handle=b.load.start(d);a.tagman.errorOK=d.errorOK?true:false;if(d.tag&&d.tag instanceof b.Tag)a.tagman.tag=d.handle;d.element=a}}else d={};if(s.body){var f;if(d.target)f=d.target;else if(d.tag)f=b.util.findById([b.position.makeName(d.tag.position),b.position.makeName(b.position.BOTTOM_BODY)]);
else if(b.client.isBodyAppendSafe()){s.body.appendChild(a);return a.id}else f=b.util.findById([b.position.makeName(b.currentPosition),b.position.makeName(b.position.BOTTOM_BODY)]);if(!f){f=s.getElementsByTagName("div");if(f.length>0)f=f[f.length-1];else if(a.nodeName=="SCRIPT")f=s.getElementsByTagName("script")[0].parentNode;else return false}try{f.insertBefore(a,null)}catch(g){if("Unexpected call to method or property access."==(g.message||g)){b.util.log("WARNING!! failed to append to "+f.tagName+
"."+f.id+", replacing element with a DIV","warning");var h=s.createElement("DIV");if(f.id)h.id=f.id;f.parentNode.replaceChild(h,f);h.insertBefore(a,null)}}}else{f=s.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}return a.id},appendIframe:function(a,d,e){var f=s.createElement("iframe");if(d){f.width="18px";f.height="18px"}else{f.width="0";f.height="0"}f.style.cssText="position:absolute;left:-999em;top:0";f.src=a;return b.util.append(f,e)},appendObject:function(a,d){var e=s.createElement("object");
e.width=e.height=1;e.style.display="none";e.data=a;return b.util.append(e,d)},appendDiv:function(a,d){if(!a){b.util.log("id compulsary for call to appendDiv, request ignored","error");return false}var e=s.createElement("div");e.id=a;if(d)e.innerHTML=d;else e.style.display="none";return b.util.append(e)},appendCSS:function(a){var d=s.getElementsByTagName("head")[0];if(!a||!d)return false;var e=s.createElement("link");e.id="tmcss_"+b.util.elements++;e.rel="stylesheet";e.type="text/css";e.href=a;e.media=
"screen";d.appendChild(e);return e.id},appendScript:function(a,d,e){if(!d&&b.syncSafe&&!b.client.canAsyncJS()&&(!e||e.defer!==false)&&b.client.canDeferJS()&&b.client.canAccelerate(b._containers?b._containers[0]:p)){e=e||{};e.defer=true;return b.util.writeScript(a,false,e)}var f=s.createElement("script");f.async=e&&e.async===false?false:true;if(d)f.text=a;else f.src=a;return b.util.append(f,e)},log:function(a,d){if(typeof b._containers!="undefined"&&b._containers[0]&&b.Log&&b._containers[0].log instanceof
b.Log)b._containers[0].log.error(a,d||"warning");else if((b.util.cookie("tmDebug")!==null||location.host==="127.0.0.1"||location.protocol==="file:")&&typeof console==="object"&&console.log)console.log("TagMan Init ["+d+"]:"+a)},getUID:function(){var a=b.num.base92encode(+new Date,7);a+=b.num.base92encode(Math.floor(Math.random()*1E4),2);a+=b.num.base92encode(b.String.checksum(navigator.userAgent),5);return a},getProtocol:function(){return location.protocol==="https:"?"https://":"http://"},appendImage:function(a,
d){var e=s.createElement("img");e.src=a;e.style.width=e.style.height=1;e.style.cssText="position:absolute;left:-999em;top:0;border:0;";return b.util.append(e,d)},killById:function(a){b.util.log("attempting to kill id "+a,"debug");if(!b.client.canKill())return false;try{var d=s.getElementById(a),e="src data text".split(" "),f=0,g,h;if(!d){b.util.log("element "+a+" not found, unable to kill","error");return false}for(;g=e[f++];)if(g in d||f==e.length){if((h=b.client[g+"Replacement"](d))!==false){b.util.log("****** killById("+
a+") - setting "+g+" of "+d.nodeName+" to "+h,"debug");d[g]=h}return true}}catch(i){b.util.log("error attempting to kill id "+a+":"+i.message,"debug")}b.util.log("***** removing node from dom: "+a+" / "+d.nodeNamei,"debug");d.parentNode&&d.parentNode.removeChild(d);return true},decode:function(a){return decodeURIComponent(a)},encode:function(a){return encodeURIComponent(a)},writeImage:function(a,d,e,f){if(!b.syncSafe){b.util.log("ignoring unsafe attempt to document.write image ["+a+"]","error");return false}var g=
"tmim_"+b.util.elements++;d='<img id="'+g+'" src="'+a+'" width="'+(d||1)+'" height="'+(e||1)+'" border="0"'+(d?"":' style="position:absolute;top:0;left:-999em"');if(f){d+=" onload=\"TMAN.load.onLoadById('"+g+"', true);\" onerror=\"TMAN.load.onLoadById('"+g+"', false);\" />";f.url=a;f.id=g;b.load.start(f)}else d+=" />";b.util.log("writing "+g+": ["+a+"]","debug");s.write(d);return g},writeJS:function(a,d){var e=b.syncSafe;b.syncSafe=true;var f=b.util.writeScript(a,!d);b.syncSafe=e;return f},writeScript:function(a,
d,e){if(!b.syncSafe&&"undefined"==typeof j.ghostwriter){b.util.log("ignoring unsafe attempt to document.write script [ "+a+" ]","warning");return false}e&&typeof e!=="object"&&b.util.log("writeScript for "+a+"loadOptions should be an object [ "+e+" ]","error");var f="tmjs_"+ +b.util.elements++;b.util.log("writing "+f+": ["+a+"]","debug");var g='<script id="'+f+'"';if(d)g+=">"+a;else{if(e&&e.defer)g+=' defer="defer"';g+=' src="'+a+'">'}g+="<\/script>";if(e&&e.onLoad&&!d){var h="var _oSS = TMAN.syncSafe; TMAN.syncSafe=true; TMAN.load.onLoadById('"+
f+"', true); TMAN.syncSafe = _oSS";e.url=a;e.id=f;b.load.start(e)}s.write(g);h&&b.hack.addDelayedWrite(h)},ghostwriteScript:function(a,d,e){var f=s.createElement("script");f.type="text/deferscript";if(d)f.text=a;else f.defersrc=a;if(e&&e.onLoad)f.done=e.onLoad;return b.util.append(f)},writeIframe:function(a,d,e){if(!b.syncSafe){b.util.log("ignoring attempt to document.write iframe ["+a+"] after dom ready","error");return false}var f="tmif_"+b.util.elements++,g='<iframe id="'+f+'" src="'+a+'" style="position:absolute;top:0;left:-999em" ';
g+=d?'width="18px" height="18px"':'width="0" height="0"';if(e){g+=" onload=\"TMAN.load.onLoadById('"+f+"', true);\" onerror=\"TMAN.load.onLoadById('"+f+"', false);\">";e.url=a;e.id=f;b.load.start(e)}else g+=">";b.util.log("writing "+f+": ["+a+"]","debug");s.write(g+"</iframe>");return f},parseKeyValue:function(a,d,e,f){d=RegExp("([^=]+?)=([^"+d+"]*?)(?:"+d+"\\s*|$)","g");var g={},h;f=e?f||b.util.decode:b.util.K;if(a.charAt(0)==="?")a=a.slice(1);for(;h=d.exec(a);){e=f(h[1]);h=f(h[2]);if(g[e]){if(typeof g[e]===
"string")g[e]=[g[e]];g[e].push(h)}else g[e]=h}return g},setKeyValue:function(a,d,e,f,g,h){h=g?h||b.util.encode:b.util.K;e=h(d)+"="+h(e);a=a.replace(RegExp("(^|"+f+"\\s*|\\?)"+h(d)+"=[^"+f+"]*?("+f+"\\s*|$)","g"),function(i,k,o){return k+e+o});return a.indexOf(e)<0?a+f+e:a},forEach:function(){function a(h,i){for(var k in this)d.call(this,k)&&h.call(i,this[k],k,this)}var d={}.hasOwnProperty,e="hasOwnProperty.isPrototypeOf.propertyIsEnumerable.toLocaleString.toString.valueOf".split("."),f=e.length,g;
for(g in{toString:true})if(g==="toString")return a;return function(h,i){a.call(this,h,i);for(var k=0,o;k<f;++k)if(d.call(this,o=e[k]))h.call(i,this[o],o,this)}}(),cookie:function(a,d,e){if((a+d).length>b.MAX_COOKIE_LENGTH)if(a.length>b.MAX_COOKIE_LENGTH){b.util.log("key exceeds "+b.MAX_COOKIE_LENGTH+" chars, unable to set: "+a,"warning");return false}else{b.util.log("attempt to set/get cookie "+a+"beyond"+b.MAX_COOKIE_LENGTH+" chars"+d,"warning");d=d.substr(0,b.MAX_COOKIE_LENGTH-a.length)}if(arguments.length>
1&&(d===null||typeof d!=="object")){e=b.util.extend({},e);if(d===null)e.expires=-1;if(typeof e.expires==="number"){var f=e.expires,g=e.expires=new Date;g.setDate(g.getDate()+f)}return s.cookie=[encodeURIComponent(a),"=",e.raw?String(d):encodeURIComponent(String(d)),e.expires?"; expires="+e.expires.toUTCString():"",e.path?"; path="+e.path:"",e.domain?"; domain="+e.domain:"",e.secure?"; secure":""].join("")}e=d||{};g=e.raw?function(h){return h}:decodeURIComponent;return(f=RegExp("(?:^|; )"+encodeURIComponent(a)+
"=([^;]*)").exec(s.cookie))?g(f[1]):null},scramble:function(a){if(a==null)return null;if(a.length==0)return a;for(var d=[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],e="",f="4!\"#$1&'()*+,-./0123456789:2<3>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}".split(e),g=a.length,h=0;h<g;h++){var i=(a.charAt(h).charCodeAt(0)+h+62)%94;if(d[i])e+=
"%";e+=f[i]}return e},unscramble:function(a){if(a==null)return null;if(a.length==0)return a;for(var d=0,e="",f=a.length,g=0,h;g<f;g++){h=a.charAt(g);if(h=="%"){g++;h=a.charAt(g);if(h=="4")h=" ";else if(h=="3")h="=";else if(h=="2")h=";";else if(h=="1")h="%";else{g--;continue}}e+=String.fromCharCode((156+h.charCodeAt(0)-d++%94)%94+32)}return e},loadScriptOnce:function(a,d,e){d=d||{};if(b.load.isLoadedByURL(a)){typeof d.onLoad==="function"&&d.onLoad(true);return true}else if(b.load.isLoadingByURL(a)){if(typeof d.onLoad===
"function"||typeof d.onError==="function"){a=b.load.getElementHandlerByURL(a);typeof d.onLoad==="function"&&a._addOnLoad(d.onLoad)}return false}else if(b.load.isDeadByURL(a))if(typeof d.error==="function"){d.onError();return false}d.url=a;if(e){b.client.useDelayedWrite();b.util.writeScript(a,false,d)}else b.util.appendScript(a,false,d)},isBody:function(){return s.body||s.getElementsByTagName("head")[0]},preCacheScript:function(a,d){d=d||{};if(b.load.isLoadedByURL(a)){typeof d.onLoad==="function"&&
d.onLoad(true);return true}else if(b.load.isLoadingByURL(a)){var e=b.load.getElementHandlerByURL(a);typeof d.onLoad==="function"&&e._addOnLoad(d.onLoad);return false}else if(b.load.isDeadByURL(a))return false;if(typeof b.client.preCacheType!=="function")return false;else{if(!b.util.isBody()&&!b.client.canHeadPrecache)return false;d.url=a;d.errorOK=true;return b.util["append"+(b.client.preCacheType()==="object"?"Object":"Image")](a,d)}},arrayIndexOf:function(a,d){if(typeof a==="object"&&a.length)if(typeof a.indexOf===
"function")return a.indexOf(d);else for(var e=a.length;e--;)if(a[e]===d)return e;return-1}};b.getUID=function(){if(!b.uid)b.uid=b.util.getUID();return b.uid};this.TMAN||(this.TMAN={});if(!b.date)b.date=function(){function a(d,e){var f=new Date,g=e?"getUTC":"get";f=new Date(f[g+"FullYear"](),f[g+"Month"](),f[g+"Date"]()+(d||0));return e?new Date(f-f.getTimezoneOffset()*6E4):f}return{today:function(d){return a(d)},todayUTC:function(d){return a(d,true)}}}();this.JSON||(JSON={});(function(){function a(q){return q<
10?"0"+q:q}function d(q){g.lastIndex=0;return g.test(q)?'"'+q.replace(g,function(w){var m=k[w];return typeof m==="string"?m:"\\u"+("0000"+w.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+q+'"'}function e(q,w){var m,u,t,F,A=h,E,l=w[q];if(l&&typeof l==="object"&&typeof l.toJSON==="function")l=l.toJSON(q);if(typeof o==="function")l=o.call(w,q,l);switch(typeof l){case "string":return d(l);case "number":return isFinite(l)?String(l):"null";case "boolean":case "null":return String(l);case "object":if(!l)return"null";
h+=i;E=[];if(Object.prototype.toString.apply(l)==="[object Array]"){F=l.length;for(m=0;m<F;m+=1)E[m]=e(m,l)||"null";t=E.length===0?"[]":h?"[\n"+h+E.join(",\n"+h)+"\n"+A+"]":"["+E.join(",")+"]";h=A;return t}if(o&&typeof o==="object"){F=o.length;for(m=0;m<F;m+=1)if(typeof o[m]==="string"){u=o[m];if(t=e(u,l))E.push(d(u)+(h?": ":":")+t)}}else for(u in l)if(Object.prototype.hasOwnProperty.call(l,u))if(t=e(u,l))E.push(d(u)+(h?": ":":")+t);t=E.length===0?"{}":h?"{\n"+h+E.join(",\n"+h)+"\n"+A+"}":"{"+E.join(",")+
"}";h=A;return t}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h,i,k={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;if(typeof JSON.stringify!=="function")JSON.stringify=function(q,w,m){var u;i=h="";if(typeof m==="number")for(u=0;u<m;u+=1)i+=" ";else if(typeof m==="string")i=m;if((o=w)&&typeof w!=="function"&&(typeof w!=="object"||typeof w.length!=="number"))throw Error("JSON.stringify");return e("",
{"":q})};if(typeof JSON.parse!=="function")JSON.parse=function(q,w){function m(t,F){var A,E,l=t[F];if(l&&typeof l==="object")for(A in l)if(Object.prototype.hasOwnProperty.call(l,A)){E=m(l,A);if(E!==p)l[A]=E;else delete l[A]}return w.call(t,F,l)}var u;q=String(q);f.lastIndex=0;if(f.test(q))q=q.replace(f,function(t){return"\\u"+("0000"+t.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(q.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){u=eval("("+q+")");return typeof w==="function"?m({"":u},""):u}throw new SyntaxError("JSON.parse");}})();b.POLL_INTERVAL||(b.POLL_INTERVAL=100);b.ElementHandler=function(a){if(!a||!a.url||!a.id){b.util.log("ElementHandler expects url & id options","Error");return false}this.url=a.url;this.elementId=a.id;this.element=a.element;var d=this;this.startTime=+new Date;this.timeOut=a.timeOut||false;this.tag=a.tag||p;this.timeOut&&this._addShouldKill(function(){return d.getTime()>=
d.timeOut});typeof a.shouldKill=="function"&&this._addShouldKill(a.shouldKill);typeof a.onLoad=="function"&&this._addOnLoad(a.onLoad);this.shouldPoll()&&b.load.startPolling()};b.ElementHandler.prototype={_finish:function(a){if(!this.endTime){this.endTime=+new Date;this.loaded=a||false;typeof this._onLoad==="function"&&this._onLoad(a);this._shouldKill=false;b.load.finishedLoading(this)}},shouldPoll:function(){return typeof this._shouldKill=="function"||b.client.useReadyState()},poll:function(){if(!this.element&&
this.elementId)try{this.element=s.getElementById(this.elementId)}catch(a){}if(this.element&&b.client.useReadyState())if(this.element.readyState&&this.element.readyState!="loading"&&this.element.readyState!=="uninitialized")this._finish(this.element.readyState=="complete"||this.element.readyState=="loaded");!this.endTime&&typeof this._shouldKill=="function"&&this._shouldKill()&&this.kill()},getTime:function(){return(this.endTime||+new Date)-this.startTime},_shouldKill:false,kill:function(){if(!this.endTime){b.util.killById(this.elementId);
this.shouldKill=false;this._finish(false)}},_addOnLoad:function(a){typeof a!=="function"&&b.util.log("_addOnLoad requires function received "+typeof a);if(this._onLoad){var d=this._onLoad;this._onLoad=function(e){d(e);a.call(this,e)};return true}else this._onLoad=a},_addShouldKill:function(a){if(typeof this._shouldKill=="function"){var d=this._shouldKill;this._shouldKill=function(){return d.call(this)||a.call(this)}}else this._shouldKill=a}};b.load=function(){function a(i){for(var k=e.slice(),o=k.length,
q=false;o&&o--;){k[o].poll();q=true}!i&&!q&&b.load.stopPolling();return q}function d(i,k,o){if(typeof k!="object")if(typeof e=="object"&&typeof f=="object")return d(i,e,o)||d(i,f,o);else{b.util.logError("TNAN.load._done,_queue are not arrays","fatal");return false}for(var q=k.length;q&q--;)if(i&&k[q].url==i||o&&k[q].elementId==o)return k[q];return false}var e=[],f=[],g=false,h=false;return{start:function(i){if(!i)return false;i=new b.ElementHandler(i);e.push(i);return i},startPolling:function(){if(!h){g=
setInterval(a,b.POLL_INTERVAL);h=true}return true},stopPolling:function(){if(h){for(var i=e.length;i--;)if(e[i].shouldPoll())return false;h=false;g=!!clearInterval(g)}return true},isPolling:function(){return g!==false},getElementHandlerByURL:function(i,k){return d(i,k,false)},getElementHandlerById:function(i,k){return d(0,k,i)},finishedLoading:function(i){i||b.util.log("loadElement not supplied to finishedLoading","error");f.push(i);e.splice(b.util.arrayIndexOf(e,i),1);h&&b.load.stopPolling()},isLoadingByURL:function(i){b.load.poll(true);
return b.load.getElementHandlerByURL(i,e)?true:false},isLoadedByURL:function(i){b.load.poll(true);if(i=b.load.getElementHandlerByURL(i,f))return i.loaded;return false},getLoadTimeByURL:function(i){if(i=b.load.getElementHandlerByURL(i,f))return i.getTime();return false},getLoadTimeById:function(i){if(i=b.load.getElementHandlerById(i,f))return i.getTime();return false},isDeadByURL:function(i){if(i=b.load.getElementHandlerByURL(i,f))return!i.loaded;return false},isDeadById:function(i){if(i=b.load.getElementHandlerById(0,
f,i))return!i.loaded;return false},isLoadingById:function(i){b.load.poll(true);return b.load.getElementHandlerById(i,e)?true:false},isLoadedById:function(i){b.load.poll(true);return(i=b.load.getElementHandlerById(i,f))&&i.loaded||false},onLoadById:function(i,k){var o=b.load.getElementHandlerById(i);if(o){o._finish(k);return true}return false},onLoadByURL:function(i,k){var o=b.load.getElementHandlerByURL(i);if(o){o._finish(k);return true}return false},onLoad:function(i){if(this===j){b.util.log("onLoad expects to be called in element context, use call(this,success)",
"error");return false}this.tagman.handle.endTime||this.tagman.handle._finish(i||this.tagman.errorOK)},reset:function(){e=[];f=[];b.load.stopPolling()},poll:a}}();b.remoteLogURL=(location.protocol==="file:"?"http:":"")+"//stats.tagman.com/";b.isTimedOut=b.isTimedOut||function(){return false};b.Log=function(a){this._options=a||(a={});var d=a.logRate||{},e,f=this._messageTypes.length;this._history=[];for(this._doLogging={};f--;){e=this._messageTypes[f];this._doLogging[e]=this._level(d[e])}this._throwErrors=
a.throwErrors||{};d=a.statRate||{};this._doStats={};for(f=this._statTypes.length;f--;){e=this._statTypes[f];this._doStats[e]=this._level(d[e])}this._logContainerStart=a.quietMode?false:true;this.writeRemotely();b.util.cookie("tmDebug")&&this.setDebugMode()};b.Log.prototype={_messageTypes:["debug","info","warning","error","fatal"],_statTypes:["tag","container","parameter"],_level:function(a){a=a||0;var d;d=a?a===100?true:b.num.doSample(a)?true:false:false;return{sampleRate:a,display:d}},displayOut:(b.util.cookie("tmDebug")!==
null||location.host==="127.0.0.1")&&typeof console==="object"&&console.log,setLogLevelRate:function(a,d){if(typeof a==="undefined"||typeof d==="undefined")this.error("level and rate must be defined","error");else this._doLogging[a]=this._level(d)},setStatTypeRate:function(a,d){if(typeof a==="undefined"||typeof d==="undefined")this.error("type and rate must be defined","error");else this._doStats[a]=this._level(d)},writeRemotely:function(){var a,d;for(a in this._doStats)if(this._doStats[a].sampleRate){d=
true;break}this.writeRemotely=!!(b.remoteLogURL&&d)},getLogging:function(a){return this._doLogging[a.toLowerCase()].display},getLogRate:function(a){return this._doLogging[a.toLowerCase()].sampleRate},getStats:function(a){return this._doStats[a.toLowerCase()].display},getStatsRate:function(a){return a&&(a=a.toLowerCase())in this._doStats?this._doStats[a].sampleRate:0},setDebugMode:function(){for(var a,d=this._messageTypes.length;d--;){a=this._messageTypes[d];this._doLogging[a]=this._level(100)}this.displayOut=
typeof console!=="undefined"&&console.log?true:false;this.writeRemotely=false;return true},_write:function(a,d){d=d?d.toLowerCase():this._messageTypes[0];var e="TagMan("+d+"):[ "+a+" ]";if(this.getLogging(d)){this.displayOut&&this.display(e);this.writeRemotely&&this.remoteWrite({lv:b.util.arrayIndexOf(this._messageTypes,d),me:a,sr:this.getLogRate(d)},"lm")}this._history.push(e);return e},display:function(a){this.displayOut&&console.log(decodeURIComponent(a))},remoteWrite:function(a,d){if(!this.writeRemotely||
!a)return false;this.containerStart();a.id=a.id||b.uid;a.ac=a.ac||this.container.account;a.po=typeof a.po!=="undefined"?a.po:b.currentPosition;var e=b.remoteLogURL+d+"?"+b.String.objectToQuery(a);b.util.appendImage(e);return e},message:function(a,d){this._write(a,d)},error:function(a,d){var e=this._write(a,d);if(this._throwErrors[d.toLowerCase()])throw Error(e);},containerStart:function(a){if(!this._logContainerStart)return false;this._logContainerStart=false;a=a||this._options||{};for(var d=0,e=
0,f;f=this._statTypes[e++];)d=Math.max(d,this.getStatsRate(f));a={rf:a.rf||location.href,sp:a.sp||b.currentPosition,as:a.as||this.container.async?1:0,bi:a.bi||this.container.baseId,ci:a.ci||this.container.id,br:a.br||b.client.getBrowser(),os:a.os||b.client.getOS(),sr:a.sr||d,lp:a.lp||this.container.isLandingPageDisabled()?1:0};this.writeRemotely?this.display(this.remoteWrite(a,"cs").substr(b.remoteLogURL.length)):this.display(b.String.objectToQuery(a));return true},tagEnd:function(a){if(a&&!(a instanceof
b.Tag))a=this.container.getTagById(a);!a instanceof b.Tag&&this.error("tagEnd required a TMAN.Tag or valid Id");if(this.getStats("tag")){a={ti:a.id,tb:a.getLoadTime(),tl:b.isTimedOut()?"p":this.container.isTimedOut()?"c":a.isTimedOut()?"t":a.isRunOnceActive()?"r":p,sr:this.getStatsRate("tag")};this.writeRemotely?this.display(this.remoteWrite(a,"te").substr(b.remoteLogURL.length)):this.display(b.String.objectToQuery(a))}},containerEnd:function(a){a=a||{};for(var d="",e="",f=this.container.tags.length,
g;f--;){g=this.container.tags[f];if(g.hasExecuted())d+=","+g.id;else e+=","+g.id}a={sr:a.sr||this.getStatsRate("container"),tl:a.tl||d.substr(1),tk:a.tk||e.substr(1),bt:a.cb||b.blockingTime,tp:a.tp||b.getPageLoadTime(),bc:a.bc||this.container.blockCalls,wl:a.wl||b.waitLatency||p};this.writeRemotely?this.display(this.remoteWrite(a,"ce").substr(b.remoteLogURL.length)):this.display(b.String.objectToQuery(a))},containerParams:function(){var a={},d;for(d in this.container.param)a[d]=this.container.param[d];
a.sr=this.getStatsRate("container");this.writeRemotely?this.display(this.remoteWrite(a,"cp")):this.display(b.String.objectToQuery(a));return false},getHistory:function(){return this._history}};C=b.storage=function(){function a(l){return{get:function(v,x){var D=l.getItem(f+v);return!D?null:(D=t(D.toString()),D.expiry<=new Date)?this.remove(v):D[x?m:u]},set:function(v,x,D){if(x===null)return this.remove(v);l.setItem(f+v,F({expiry:d(D||g),data:x}));return x},remove:function(v){l.removeItem(f+v);return null},
clear:function(){for(var v=0,x=RegExp("^"+f),D;v<l.length;)if(x.test(D=l.key(v)))l.removeItem(D);else v++}}}function d(l){return typeof l=="number"?(new Date).getTime()+(l|0)*1E3:l instanceof Date?l.getTime():(new Date).getTime()+g*1E3}var e,f="__test",g=1800,h,i="localStorage globalStorage userData cookies".split(" "),k=0,o,q,w=location.hostname,m="expiry",u="data",t=JSON.parse,F=JSON.stringify,A={get:function(l,v){return e.get(l,v)},set:function(l,v,x){return e.set(l,v,x)},remove:function(l){return e.remove(l)},
clear:function(){return e.clear()},getExpiry:function(l){return!arguments.length?g:e.get(l,true)},setExpiry:function(l,v){var x;if(arguments.length===2)return(x=this.get(l))!==null?this.set(l,x,v):x;if(arguments.length===1)g=A._expiry=l|0},store:function(l,v,x){if(v===null)return this.remove(l);if(arguments.length==1)return this.get(l);if(arguments.length>1)return this.set(l,v,x)},setType:function(l){var v=i.join(",");if(l&&v.indexOf(l)>-1&&l in A&&h!=l){e=A[this._type=h=l];e.init&&e.init();return true}return false},
getType:function(){return h},_prefix:f,_expiry:g,cookies:{get:function(l,v){var x=s.cookie.match(RegExp("(?:^|; )"+f+l+"=([^;]+)"));return x&&t(decodeURIComponent(x[1]))[v?m:u]||null},set:function(l,v,x){if(v===null)x=-1E9;x=d(x||g);l=[f+l+"="+encodeURIComponent(F({expiry:x,data:v})),"path=/"];l.push("expires="+(new Date(x)).toUTCString());s.cookie=l.join("; ");return v},remove:function(l){return this.set(l,null)},clear:function(){for(var l=s.cookie.split(";"),v,x=0,D=RegExp("(?:^| )"+f+"([^ =;]+)=([^;]+)");v=
l[x++];)if(v=v.match(D))this.remove(v[1])}}};for(;k<2&&(o=i[k++]);)try{q=o=="globalStorage"?j[o][w+(w.indexOf(".")<0?".localdomain":"")]:j[o];if(q.getItem&&q.setItem&&q.removeItem)A[o]=a(q)}catch(E){}if(s.documentElement.addBehavior)A.userData=function(){var l,v,x=function(y){return y.replace(/[^0-9a-zA-Z-_.]+/g,"-")},D=function(){l.setAttribute("tman-keys",F(v));l.save("tman-keys")};return{init:function(){var y=s.head||s.getElementsByTagName("head")[0]||s.documentElement;l=this._element=s.createElement("div");
l.addBehavior("#default#userdata");l.style.display="none";y.insertBefore(l,y.firstChild);l.load("tman-keys");v=(y=l.getAttribute("tman-keys"))&&t(y)||{}},set:function(y,N,K){if(N===null)return this.remove(y);l.setAttribute(y=x(y),F({expiry:d(K||g),data:N}));v[y]=1;D();return N},get:function(y,N){var K=l.getAttribute(y=x(y));return!K?null:(K=t(K),K.expiry<=new Date)?this.remove(y):K[N?m:u]},remove:function(y){l.removeAttribute(y=x(y));delete v[y];D();return null},clear:function(y){for(y in v){l.removeAttribute(y);
delete v[y]}D()},save:D,_suffix:""}}();for(k=0;o=i[k++];)if(A.setType(o))break;return A}();b.Session=function(a,d,e){if(typeof a!=="string")throw Error("account must be a string");this.account=a;a=+new Date;this.initTime=typeof e!=="undefined"?e:a;this.timeout=typeof d!=="undefined"?d:1800};b.Session.prototype={isActive:function(){if(typeof this._isActive==="boolean")return this._isActive;return this._isActive=!this.isNewSession()},_setLastActive:function(){var a="TMLA_"+this.account;this._nowInSecs=
Math.floor(this.initTime/1E3);this._lastActive=C.get(a);C.set(a,this._nowInSecs)},isNewSession:function(){this._setLastActive();if(!this._lastActive)return true;if(this._nowInSecs-this._lastActive>this.timeout)return true;return false}};if(!b.String){b.String=function(a){this.value=a};b.String.prototype={replaceIfMatch:function(a,d){var e=this.value.match(a);if(!e){this.value="";return this}e=e[0];if(!d){this.value=e;return this}this.value=e.replace(a,d);return this},replace:function(a,d){this.value=
this.value.replace(a,d);return this},toString:function(){return this.value},callIfMatch:function(a){for(var d=1,e=arguments.length;d<e;d++)if(this.value.match(arguments[d]))return a()}};b.String.escape=function(a){return escape(a).replace(/\//g,"%2F")};b.String.doubleEscape=function(a,d){var e=b.String.escape(b.String.escape(a));return d?e.replace(RegExp("^(.{1,"+d+"})(?:%25.*|$)"),"$1"):e};b.String.getParam=function(a,d){return a&&d&&b.util.parseKeyValue(a,"&",false)[d]};b.String.setParam=function(a,
d,e){var f=b.util.parseKeyValue(a||"?","&",false);f[d]=e;return(a.charAt(0)==="?"?"?":"")+b.String.objectToQuery(f)};b.String.objectToQuery=function(a){typeof a!="object"&&b.util.log("objectToQuery not passed object: "+a,"debug");var d=[],e;for(e in a)d.push("&",encodeURIComponent(e),"=",encodeURIComponent(a[e]));return d.slice(1).join("")};b.String.queryToObject=function(a){return b.util.parseKeyValue(a||"?","&",true)};b.String.subString=function(a,d,e){var f="".substr;return e?f.call(a||"",d,e):
f.call(a||"",d)};b.String.regEx=function(a,d){if(a&&d){var e=RegExp(d).exec(a);if(e){e.splice(0,1);return e.join("")}}return""};b.String.isFound=function(a,d){if(a&&d)return a.indexOf(d)==-1?0:1;return 0};b.String.printR=function(a,d){var e=[],f=Array(d?++d:d=1).join("\t");if(a==null)e.push(f,a===null?"null":"undefined","<br>");else switch(typeof a){case "function":case "string":a=(""+a).replace(/</g,"&lt;").replace(/(\r\n|\n|\r)/g,"$1"+f);case "boolean":case "number":e.push(f,a,"<br>");break;default:if(a.length){e.push(f,
"ArrayObject<br>");for(var g=0,h=a.length;g<h;++g)e.push(f,"[",g,"] ",b.String.printR(a[g],d).toString().replace(/^\s+/,""),"<br>")}else{e.push(f,a.name||"Generic"," Object<br>");for(g in a)e.push(f,"['",g,"'] ",b.String.printR(a[g],d).toString().replace(/^\s+/,""),"<br>")}}return e.join("").replace(/<br><br>/g,"<br>")};b.String.getStem=function(a,d){if(a&&d){var e="";d=","+d+",";for(var f=a.split("/"),g=f.length*-1,h=0;h<f.length;h+=1){if(d.indexOf(","+h+",")>-1||d.indexOf(","+g+",")>-1){if(e)e+=
"/";e+=f[h]}g+=1}return e}};b.String.trim=function(a){a=a.replace(/^\s\s*/,"");for(var d=/\s/,e=a.length;d.test(a.charAt(--e)););return a.slice(0,e+1)};b.String.checksum=function(a){for(var d=0,e=a.toString().length;e&&e--;)d+=a.charCodeAt(e)*(e+1);return d}}if(typeof b=="undefined")b={};b.StringBuilder=function(){function a(){}var d=Array.prototype.join;a.prototype={constructor:a,length:0,push:Array.prototype.push,append:Array.prototype.push,size:function(){return this.toString().length},toString:function(){return d.call(this,
"")}};return a}();if(!b.num)b.num={getCacheBuster:function(a){return(Math.random()+"").substr(2,a)},doSample:function(a){return(Math.random()*100<=(a||0))>>0},base26Encode:function(a){var d="";do{d=String.fromCharCode(a%26+65)+d;a=a/26-1}while(a>=0);return d},base26Decode:function(a){for(var d=a.length-1,e=1,f=a.charCodeAt(d)-65;--d>=0;){e*=26;f+=e*(a.charCodeAt(d)-64)}return f},base92encode:function(a,d){function e(o){var q=o.length,w=Array(q*2),m=0,u=0,t=0;for(t=0;t<q*2;t++){m<<=16;w[t]=t%2==0?
o[u]>>16&65535|m:o[u++]&65535|m;m=w[t]%92;w[t]=w[t]/92|0}o=Array(q);for(t=0;t<q;t++)o[t]=w[t*2]<<16|w[t*2+1];f=m;return o}var f;if(!d){for(var g=0;Math.pow(92,g++)<a;);d=g-1}if(typeof a!="array")a=a.toString().split("");var h=a.length,i=Array(h);g=Array(d);var k=0;for(k=0;k<h;k++)i[k]=a[k];for(k=f=0;k<d;k++){i=e(i);g[k]=f}for(h="";d>0;){k=g[--d];h+=k>58?String.fromCharCode(k+34):k>1?String.fromCharCode(k+33):String.fromCharCode(k+32)}return h}};(function(){function a(m){if((m=d(m))&&m.innerHTML)try{Function(m.innerHTML)()}catch(u){LEVU.LE('Error in `evaluateScript`. Script contents: "'+
m.innerHTML+'"',"Error")}}function d(m){for(var u=s.getElementsByTagName("script"),t=u.length;t--;)if(u[t].src.indexOf("/"+m)>-1)return u[t];return""}function e(m){var u=d(m);if(u){var t=u.src.indexOf("/"+m+"?");if(t>-1)return u.src.substr(t+m.length+2)}return""}function f(m,u,t){if(!b.syncSafe){b.util.log("Attempt to added delayed write when not syncSafe: "+m,"error");return false}if(m){if(typeof m==="function")m="("+m.toString()+")();";else if(b.String.trim(m).substr(-1)!==";")m+=";";if(t&&t.onLoad)m+=
typeof t.onLoad==="function"?"("+t.onLoad.toString()+")();":"loadOptions.onLoad;";if(b.client.useDelayedWrite()){u?o.unshift(m):o.push(m);b.util.log("Adding to "+(u?"start":"end")+" of delayed write queue of size ("+o.length+" inc) : "+m.toString(),"debug");g()}else{if(!m){b.util.log("addDelayedWrite called without code argument","error");return}b.util.writeScript(m,true)}return true}else b.util.log("addDelayedWrite called without code argument","error")}function g(){if(o.length&&!q){b.util.log("delayed write block "+
w+" inserted","debug");var m=b.util.getProtocol(),u;if(m==="file://")m="http://127.0.0.1";else{u=m==="https://"?k:i;m=m+u}typeof LEVU=="undefined"?b.util.writeJS(m+"/js/TMAN.hack.WDW.js",1):b.util.writeJS(m+"/js/LEVU.WDW.xjs",1);q=true}}function h(){var m=b.syncSafe;b.syncSafe=true;q=false;var u=o.length,t;if(o.length){t=o.shift();b.util.log("delayed write executing block "+w++ +" : "+t.toString(),"debug");var F=b.syncSafe;b.syncSafe=true;typeof t==="function"?t():b.util.writeScript(t,true);b.syncSafe=
F}u>1&&g();b.syncSafe=m}var i="res.levexis.com",k="sec.levexis.com",o=[],q=false,w=1;if(!b.hack)b.hack={evalScript:a,findScript:d,getScriptParams:e,addDelayedWrite:f,initDelayedWrite:g,writeDelayedWrite:h,WDW:h}})();var L=function(){var a=function(){};a.prototype={otag:"{{",ctag:"}}",pragmas:{},buffer:[],pragmas_implemented:{"IMPLICIT-ITERATOR":true},context:{},render:function(d,e,f,g){if(!g){this.context=e;this.buffer=[]}if(!this.includes("",d))if(g)return d;else{this.send(d);return}d=this.render_pragmas(d);
d=this.render_section(d,e,f);if(g)return this.render_tags(d,e,f,g);this.render_tags(d,e,f,g)},send:function(d){d!=""&&this.buffer.push(d)},render_pragmas:function(d){if(!this.includes("%",d))return d;var e=this;return d.replace(RegExp(this.otag+"%([\\w-]+) ?([\\w]+=[\\w]+)?"+this.ctag),function(f,g,h){if(!e.pragmas_implemented[g])throw{message:"This implementation of mustache doesn't understand the '"+g+"' pragma"};e.pragmas[g]={};if(h){f=h.split("=");e.pragmas[g][f[0]]=f[1]}return""})},render_partial:function(d,
e,f){d=this.trim(d);if(!f||f[d]===p)throw{message:"unknown_partial '"+d+"'"};if(typeof e[d]!="object")return this.render(f[d],e,f,true);return this.render(f[d],e[d],f,true)},render_section:function(d,e,f){if(!this.includes("#",d)&&!this.includes("^",d))return d;var g=this;return d.replace(RegExp(this.otag+"(\\^|\\#)\\s*(.+)\\s*"+this.ctag+"\n*([\\s\\S]+?)"+this.otag+"\\/\\s*\\2\\s*"+this.ctag+"\\s*","mg"),function(h,i,k,o){h=g.find(k,e);if(i=="^")return!h||g.is_array(h)&&h.length===0?g.render(o,e,
f,true):"";else if(i=="#")return g.is_array(h)?g.map(h,function(q){return g.render(o,g.create_context(q),f,true)}).join(""):g.is_object(h)?g.render(o,g.create_context(h),f,true):typeof h==="function"?h.call(e,o,function(q){return g.render(q,e,f,true)}):h?g.render(o,e,f,true):""})},render_tags:function(d,e,f,g){var h=this,i=function(){return RegExp(h.otag+"(=|!|>|\\{|%)?([^\\/#\\^]+?)\\1?"+h.ctag+"+","g")},k=i(),o=function(w,m,u){switch(m){case "!":return"";case "=":h.set_delimiters(u);k=i();return"";
case ">":return h.render_partial(u,e,f);case "{":return h.find(u,e);default:return h.escape(h.find(u,e))}};d=d.split("\n");for(var q=0;q<d.length;q++){d[q]=d[q].replace(k,o,this);g||this.send(d[q])}if(g)return d.join("\n")},set_delimiters:function(d){d=d.split(" ");this.otag=this.escape_regex(d[0]);this.ctag=this.escape_regex(d[1])},escape_regex:function(d){if(!arguments.callee.sRE)arguments.callee.sRE=RegExp("(\\/|\\.|\\*|\\+|\\?|\\||\\(|\\)|\\[|\\]|\\{|\\}|\\\\)","g");return d.replace(arguments.callee.sRE,
"\\$1")},find:function(d,e){d=this.trim(d);var f;if(e[d]===false||e[d]===0||e[d])f=e[d];else if(this.context[d]===false||this.context[d]===0||this.context[d])f=this.context[d];if(typeof f==="function")return f.apply(e);if(f!==p)return f;return""},includes:function(d,e){return e.indexOf(this.otag+d)!=-1},escape:function(d){d=String(d===null?"":d);return d.replace(/&(?!\w+;)|["'<>\\]/g,function(e){switch(e){case "&":return"&amp;";case "\\":return"\\\\";case '"':return"&quot;";case "'":return"&#39;";
case "<":return"&lt;";case ">":return"&gt;";default:return e}})},create_context:function(d){if(this.is_object(d))return d;else{var e=".";if(this.pragmas["IMPLICIT-ITERATOR"])e=this.pragmas["IMPLICIT-ITERATOR"].iterator;var f={};f[e]=d;return f}},is_object:function(d){return d&&typeof d=="object"},is_array:function(d){return Object.prototype.toString.call(d)==="[object Array]"},trim:function(d){return d.replace(/^\s*|\s*$/g,"")},map:function(d,e){if(typeof d.map=="function")return d.map(e);else{for(var f=
[],g=d.length,h=0;h<g;h++)f.push(e(d[h]));return f}}};return{name:"mustache.js",version:"0.3.1-dev",to_html:function(d,e,f,g){var h=new a;if(g)h.send=g;h.render(d,e,f);if(!g)return h.buffer.join("\n")}}}();this.TMAN=this.TMAN||{};b.onDomReady=b.onDomReady||function(){function a(k){f?k():g.push(k)}function d(){if(!f){f=true;if(b.conf&&b.conf.param)b.conf.param.tmdom=1;for(clearInterval(i);g.length;)g.shift()();if(typeof h.readyState!=="string")h.readyState="complete"}}function e(){/^(?:loaded|complete)$/i.test(h.readyState)&&
d()}var f=false,g=[],h=s,i=0;a.isReady=function(){return f};switch(true){case !!h.addEventListener:h.addEventListener("DOMContentLoaded",d,false);j.addEventListener("load",d,false);h.addEventListener("readystatechange",e,false);break;case !!h.attachEvent:h.attachEvent("onreadystatechange",e,false);j.attachEvent("onload",d,false);case j.frameElement==null&&!+"\u000b1":i=setInterval(function(){try{h.documentElement.doScroll("left")}catch(k){return}d()},15)}i||(i=setInterval(e,b.POLL_INTERVAL||100));
b.isDomReady=false;a(function(){b.isDomReady=true});return a}();b.conf={host:"gslb.tagman.com",async:false,tagsBlockingTimeout:false,sessionTimeout:0,bootstrap:true,enableJSCall:true,campaign:true,serverCall:"",landingPageContainer:false,storageType:"cookie",version:3,cdn:"res.levexis.com",waitService:"wt.tagman.com",statRate:0,statPosition:32,tagAcceleration:false,debugMode:false,tags:{}};n.prototype={_setOptions:function(a){this._setOptionsFromDefault("async bootstrap campaign cdn enableJSCall host landingPageContainer serverCall sessionTimeout statPosition statRate storageType tagsBlockingTimeout version waitService tagAcceleration".split(" "),
a,b.conf)},_setOptionsFromDefault:function(a,d,e){for(var f=0,g;g=a[f++];)this[g]=g in d?d[g]:e[g]},addTags:function(){Array.prototype.push.apply(this.tags,arguments);for(var a=0,d;d=arguments[a++];){d.account=this.account;d.container=this;if(d.requiredScripts.length&&d.async&&!d.executeRequiredScripts){this.log.error("async scripts must execute required scripts, setting flag for tag "+d.id+" to execute","warning");d.executeRequiredScripts=true}if(b._secure!==d.secure){d.setTimedOut("security");this.log.error("tag + "+
d.id+" timed out as TMAN._secure ("+b._secure+") does not match tag.secure ("+d.secure+").","warning")}}},addParams:function(a){for(var d in a)this.param[d]=a[d]},getParams:function(){return this.param},getTagById:function(a){for(var d=this.tags.length;d--;)if(this.tags[d].id==a)return this.tags[d]},isTimedOut:function(){if(this.tagsBlockingTimeout)return b.blockingTime>=this.tagsBlockingTimeout;return false},isLandingPageDisabled:function(){return!!(this.landingPageContainer&&this.isActive())},_setSession:function(){this.session=
new b.Session(this.account,this.sessionTimeout,this.initTime)},isActive:function(){return this.session.isActive()},_performServerCall:function(){return false},fetchTagDefinitions:function(a,d){b.tagLibrary.fetchTagDefinitions(this.account,a,d)},initTagsFromMapping:function(){b.tagLibrary.initTagsFromMapping(this.account)},getHighestTagId:function(){return b.tagLibrary.getHighestTagId(this.account)},enableAcceleration:function(){this.tagAcceleration=true},disableAcceleration:function(){this.tagAcceleration=
false}};b.Container=n;b._containers=[];b.account={};b.addContainer=function(a){if(arguments.length>2&&!(arguments[0]instanceof b.Container))a=new b.Container(arguments[0],arguments[1],arguments[2]);if(!a instanceof b.Container){b.util.log("container not passed to addContainer","fatal");return false}else if(b.getContainerByName(a.account)){b.util.log("container already exists for "+a.account,"fatal");return false}b._containers.push(a);b.account[a.account]=b._containers[b._containers.length-1];a.initTime=
+new Date;a.storageType==="cookie"&&C.setType("cookies");a._setSession();a.log.containerStart();if(a.campaign&&typeof b.Track==="function")a.track=new b.Track(a,a.options);if(typeof b.tm2initialise==="function"){b.tm2initialise(a);b.tm2initialise=null}else a.serverCall&&a._performServerCall();return true};b.addParams=function(a,d){if(!a&&d){b.util.log("TMAN.addParams requires a container,params","error");return false}b.getContainerByName(a).addParams(d)};b.getParams=function(a){if(!a){b.util.log("TMAN.getParams requires a container or container name",
"error");return false}if(typeof a==="string")a=b.getContainerByName(a);if(!a){b.util.log("Container does not exist. Can't retrieve params for it.","error");return false}return a.param};b.failOrDefer=function(){return b._doTagsCallback?b.Tag.globals.HOW_FAIL:b.Tag.globals.HOW_DEFER};b.doTags=function(a,d,e){try{if(a===b.position.DOTAGS_TIMER)a=b.position.WINDOW_LOADED;b._doTagsCallback=false;e="hmm"===e;if(!e)b._doTagsCallback=true;b.currentPosition=a;b.syncSafe=typeof d=="boolean"?d?false:true:b.isDomReady?
false:true;d=0;for(var f=b._containers.length;d<f;d++){var g=b._containers[d];if(g.isLandingPageDisabled())g.log.error("doTags("+a+") disabled due to landing page","info");else if(g.isTimedOut()){g.log.error("doTags("+a+") disabled due to container blocking timeout","info");b.currentPosition===g.statPosition&&g.log.containerEnd()}else{b.currentPosition===g.statPosition&&g.log.containerEnd();var h=g.tags;b.util.log("running doTags"+(e?" CALLBACK":"")+" for "+g.account+" @ position "+b.position.makeName(a)+
" (syncSafe = "+b.syncSafe+")","debug");for(var i=h.length;i&&i--;){var k=h[i];if(!k.hasExecuted()||k.repeatable){b.util.log("doTags looking at tag ("+k.id+")","debug");k.preloadResources();if(a<=b.position.WINDOW_LOADED)k.position<=a&&k.execute();else if(k.position==a){if(!k.movable){b.util.log("changing post-WINDOW_LOADED tag to movable ("+k.id+")","debug");k.movable=true}if(!k.repeatable||!e)k.execute()}}}}}if(b._doTagsCallback){var o="TMAN.doTags("+b.currentPosition+","+(b.syncSafe?"false":"true")+
", 'hmm');";b.syncSafe?b.hack.addDelayedWrite(o):setTimeout(o,b.POLL_INTERVAL*2)}else b.syncSafe&&b.hack.addDelayedWrite("TMAN.syncSafe = false;");return true}catch(q){b.util.log("Exception in doTags: "+q,"error");return false}};b.getContainerByName=function(a){for(var d=b._containers.length;d--;)if(b._containers[d].account===a)return b._containers[d]};b.getParam=function(a,d){if(arguments.length==0){b.util.log("TMAN.getParam requires name","error");return false}d=typeof d==="string"?b.getContainerByName(d):
b._containers[0];if(!d instanceof b.Container){b.util.log("Container does not exist. Can't retrieve param for it.","error");return false}return(typeof d.param[a]==="function"?d.param[a]():d.param[a])||""};b.addParam=function(a,d){if(!b._containers||!b._containers[0]instanceof b.Container){b.util.log("no container to add ["+a+"] to","warning");return false}var e={};e[a]=d;b._containers[0].addParams(e);return true};b.reset=function(){b._containers=[];b.uid=p;b.account={};b.load.reset();b.blockingTime=
0;b.currentPosition=0};b.position={PRE_HEAD:0,TOP_HEAD:1,BOTTOM_HEAD:2,TOP_BODY:3,BOTTOM_BODY:31,DOM_COMPLETE:32,WINDOW_LOADED:33,END:64,DOTAGS_TIMER:1E3};b.position.getName=function(a){for(var d in b.position)if(b.position[d]==a)return d;return false};b.position.makeName=function(a){var d=b.position.getName(a);if(!d)return a;return"TMAN_"+d};if(j.addEventListener)j.addEventListener("load",r,false);else j.attachEvent&&j.attachEvent("onload",r);b.POLL_INTERVAL||(b.POLL_INTERVAL=100);b.Tag=function(a,
d){if(arguments.length<1)b.util.log("`code` argument is required","error");else{for(var e in d)typeof b.Tag.conf[e]=="undefined"&&b.util.log("Invalid property passed to Tag constructor: "+e,"warning");d||(d={});this.id=d.id||b.getTagId();this.code=a;this.position=typeof d.position!=="undefined"?d.position:0;this.target="target"in d?d.target:null;this.async="async"in d?d.async:false;this.movable="movable"in d?d.movable:true;this.repeatable=d.repeatable&&this.position>b.position.WINDOW_LOADED||b.Tag.conf.repeatable;
this.reference=d.reference;this.bootstrapper=d.bootstrapper||b.Tag.conf.bootstrapper;this.canExecute=typeof d.canExecute==="undefined"?B:typeof d.canExecute==="function"?d.canExecute:function(){return d.canExecute};this.timeout=typeof d.timeout!="undefined"?d.timeout:0;this.pageLoadTimeout=d.pageLoadTimeout||false;if(typeof d.secure=="undefined")this.secure=location.protocol=="https:";else if(typeof d.secure!="boolean"){b.util.log("TAG.secure should be a boolean for id "+this.id,"error");this.secure=
d.secure=="false"?false:true}else this.secure=d.secure;if("runOnce"in d)this.runOnce=typeof d.runOnce==="number"?new Date+d.runOnce*1E3:b.date.today(1);this.executeRequiredScripts="executeRequiredScripts"in d?d.executeRequiredScripts:false;this.requiredScripts=d.requiredScripts?typeof d.requiredScripts!=="object"?[d.requiredScripts]:d.requiredScripts:[];this._requiredScriptsLoadResults={};this._hasExecuted=false;this._executedAt=0;this._loaded=false}};b.Tag.globals={HOW_FAIL:false,HOW_DEFER:true,
HOW_APPEND:"ap",HOW_DOCWRITE:"dw",HOW_GHOSTWRITE:"gw"};b.Tag.conf={id:1,async:false,requiredScripts:"",executeRequiredScripts:false,timeout:0,pageLoadTimeout:false,canExecute:function(){return true},runOnce:b.date.today(1),secure:"auto detect",reference:"",position:"",target:null,movable:"",repeatable:false,bootstrapper:false};b.getTagId=function(a){return function(){return b.num.base26Encode(a++)}}(0);b.Tag.prototype={setExecutedAt:function(a){if(!this._hasExecuted||this.repeatable){this._executedAt=
a;this._hasExecuted=true}else this.logError('setExecutedAt called with "'+a+'" but status was already '+this._executedAt+" (id: "+this.id+")","debug")},getExecutedAt:function(){return this._executedAt},hasExecuted:function(){return this._hasExecuted},logError:function(a,d){if(this.container&&this.container.log)this.container.log.error(a,d);else if(b.util&&b.util.log)b.util.log(a,d);else return false;return true},determineHowAndWhere:function(){var a=where=null;if(this.target){where=b.util.findById(this.target);
if(!where){this.logError("target of "+this.target+" not found, cannot execute (id: "+this.id+")","debug");return b.Tag.globals.HOW_FAIL}}a=b.position.makeName(this.position);if(b.util.findById(a)==null&&!this.movable&&(this.position==b.position.DOM_COMPLETE||this.position==b.position.WINDOW_LOADED))a=b.position.makeName(b.position.BOTTOM_BODY);var d="undefined"!=typeof j.ghostwriter;if(this.async)if(this.target)a=b.Tag.globals.HOW_APPEND;else if(b.syncSafe)if(this.movable){where=s.getElementsByTagName("SCRIPT")[0].parentNode;
a=b.Tag.globals.HOW_APPEND}else if(this.position==b.currentPosition)a=b.Tag.globals.HOW_DOCWRITE;else{where=b.util.findById(a);if(!where){this.logError("no element with id "+a+", cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}a=b.Tag.globals.HOW_APPEND}else{if(this.movable)where=s.getElementsByTagName("SCRIPT")[0].parentNode;else{where=b.util.findById(a);if(!where){this.logError("no element with id "+a+", cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}}a=b.Tag.globals.HOW_APPEND}else if(b.syncSafe)if(this.target||
!this.movable&&this.position!=b.currentPosition)if(d){this.logError("deferring execution until DOM_COMPLETE then ghostwrite (id: "+this.id+")","debug");return b.Tag.globals.HOW_DEFER}else{this.logError("ghostwriter unavailable to write retroactively, cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}else a=b.Tag.globals.HOW_DOCWRITE;else{if(this.bootstrapper)return b.Tag.globals.HOW_DEFER;if(d){if(!this.target)if(this.movable)where=s.getElementsByTagName("SCRIPT")[0].parentNode;else{where=
b.util.findById(a);if(!where){this.logError("no element with id "+a+", cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}}a=b.Tag.globals.HOW_GHOSTWRITE}else{this.logError("ghostwriter unavailable, cannot execute (id: "+this.id+")","debug");return b.failOrDefer()}}if(d&&b.Tag.globals.HOW_APPEND===a)a=b.Tag.globals.HOW_GHOSTWRITE;return{how:a,where:where}},execute:function(){b.util.log("execute called for tag ("+this.id+") async="+this.async+", movable="+this.movable+", position="+
b.position.makeName(this.position)+", target="+this.target+", repeatable="+this.repeatable+", executed="+this.hasExecuted(),"debug");this.checkTimedOut("page");if(this.hasExecuted()&&!this.repeatable||this.isTimedOut()){this.logError("already executed or timedout (id: "+this.id+")","debug");return false}if(!this.async&&this.container.isTimedOut()){this.setTimedOut("container");this.logError("container timedout tag (id: "+this.id+")","debug");return false}var a=this.determineHowAndWhere();if(a===b.Tag.globals.HOW_FAIL){this.setExecutedAt(-b.currentPosition);
return false}else if(a===b.Tag.globals.HOW_DEFER)return false;else if(null===a){this.logError("determineHowAndWhere returned null, cannot execute (id: "+this.id+")","debug");this.setExecutedAt(-b.currentPosition);return false}if(!this.canExecute()){this.logError("canExecute condition not satisfied for tag (id: "+this.id+")","debug");return false}if(!this.isReadyToExecute())if(!this.async&&b.client.canWait()){if(this.timeout!==0){this.logError("calling blockTag because our timeout="+this.timeout+" (id: "+
this.id+")","debug");b.blockTag(this.id,this.account);return true}if(this.movable){this.logError("not ready to execute but movable so reattempt later (id: "+this.id+")","debug");return false}if(!b._doTagsCallback){this.logError("setting this tag as timed out (id: "+this.id+")","debug");this.setTimedOut("tag")}this.logError("tag waiting for required scripts so not ready to execute (id: "+this.id+")","debug");return true}if(this.isRunOnceActive())this.logError("runOnceActive says we've already run (id: "+
this.id+")","debug");else{this.starttimeoutTimer();switch(a.how){case b.Tag.globals.HOW_DOCWRITE:this.logError("injecting tag (id: "+this.id+")","debug");this._injectTag();break;case b.Tag.globals.HOW_APPEND:this.logError("injecting tag into "+a.where.tagName+"."+a.where.id+" (id: "+this.id+")","debug");this._injectTag(a.where);break;case b.Tag.globals.HOW_GHOSTWRITE:this.logError("ghostwriting tag into "+a.where.tagName+"."+a.where.id+" (id: "+this.id+")","debug");this._ghostwriteTag(a.where);break;
default:this.logError('unexpected how "'+a.how+"\", won't execute (id: "+this.id+")","debug")}this.setExecutedAt(b.currentPosition);this.runOnce&&this.setRunOnceActive();this.async&&this.logFinished();return this.hasExecuted()}},logFinished:function(){var a=new Date;this._executionTime=this.startTime?a-this.startTime:0;this.logError(this.id+" end time "+a.getTime(),"debug");b.blockingTime+=this._executionTime;this.container.log.tagEnd(this)},starttimeoutTimer:function(){if(this.timeout&&!this._timedOut===
p){var a=this;this._timedOut=false;this.logError("Starting timer of ("+this.timeout+"ms) for tag (id: "+this.id+")","debug");setTimeout(function(){this.hasExecuted()||a.logError("Timer alarm and tag "+a.id+" not yet executed","debug");a.setTimedOut()},this.timeout)}},setStartTime:function(){if(!("startTime"in this)){this.startTime=+new Date;this.logError(this.id+" start time "+this.startTime,"debug")}},_ghostwriteTag:function(a){ghostwriter(a,{insertType:"append",script:{text:this.getCode()}});return true},
_injectTag:function(a){if(this.async)return!!b.util.appendScript(this.getCode(),true,{tag:this,target:a,noOnload:true});else{a=this.getCode();this.startTime||(a="TMAN.getTag('"+this.id+"','"+this.container.account+"').setStartTime();"+a);if(b.String.trim(a).substr(-1)!=";")a+=";";a+="\n";a+="TMAN.hack.addDelayedWrite( \"TMAN.getTag('"+this.id+"','"+this.container.account+"').logFinished();\",true);";b.hack.addDelayedWrite(a,true);return true}},getCode:function(){var a=this.account;return this.code.replace(/\{\{(.*?)\}\}/g,
function(d,e){return b.getParam(e,a)})},checkTimedOut:function(){if(this._timedOut)return true;else if(this.hasExecuted())return false;if((!this.timeOutType||this.timeOutType=="page")&&this.pageLoadTimeout&&b.getPageLoadTime()>this.pageLoadTimeout)this.setTimedOut("page");else if((!this.timeOutType||this.timeOutType=="tag")&&this.timeout!==false)this.getElapsed()>this.timeout&&this.setTimedOut("tag");return this._timedOut||false},isTimedOut:function(){return this._timedOut||false},getElapsed:function(){if(!this.startTime)return 0;
if(!this.hasExecuted()&&!this._timedOut)this._executionTime=new Date-this.startTime;return this._executionTime},setTimedOut:function(a){this._timedOut=true;this._timeoutType=this._timeoutType||a||"tag";if(!this.hasExecuted()){this.logError("Tag "+this.id+" timed out ("+this._timeoutType+") after "+this.getElapsed()+"ms","warning");this.logFinished();b.load.poll(true)}},isReadyToExecute:function(){if(!this.async&&!b.client.canAccelerate(this.container)){this.requiredScripts.length&&b.util.log("tagAcceleration disabled ["+
this.id+"] always ready to execute");return true}for(var a=this.requiredScripts.length;a&&a--;)if(!this._requiredScriptsLoadResults[this.requiredScripts[a]])return false;return true},_getTagRunOnceUID:function(){return"TMRO_"+this.container.account+this.id},setRunOnceActive:function(){this.runOnce&&C.set(this._getTagrunOnceUID(),{LR:+new Date})},isRunOnceActive:function(){if(!this.runOnce)return false;var a=C.get(this._getTagRunOnceUID());if(!a)return false;return new Date-a.LR<this.runOnce},preloadResources:function(){if(!(!this.requiredScripts.length||
this.startedPreload||!this.executeRequiredScripts&&(this.async||!b.client.canPrecache(b.currentPosition)))){this.startedPreload=true;for(var a=this.requiredScripts.length;a--;)this.preloadResource(this.requiredScripts[a])}},preloadResource:function(a){var d;this._requiredScriptsLoadResults[a]=false;if(this.executeRequiredScripts){this.logError("preloading ["+a+"] for tag "+this.id+" at pos "+b.currentPosition,"debug");d=b.util.loadScriptOnce;b.client.canAccelerate(this.container)||this.logError("preloading syncronously as tag acceleration disabled ( tag "+
this.id+" at pos )","info")}else{if(!b.client.canAccelerate(this.container)){this.logError("precaching disabled ["+a+"] for tag "+this.id+" at pos "+b.currentPosition,"info");return false}this.logError("precaching ["+a+"] for tag "+this.id+" at pos "+b.currentPosition,"debug");d=b.util.preCacheScript}d(a,{tag:this,onLoad:function(e){if(!(this instanceof b.ElementHandler))throw Error("onload call in wrong context");b.util.log("onload call for "+this.url+":"+this.tag.id+" (success: "+e+")");if(e){this.tag.logError("Loaded ["+
this.url+"] for tag "+this.tag.id,"debug");this.tag._requiredScriptsLoadResults[this.url]=true;if(b.client.isExecSafeOnload()||this.tag.async)this.tag.execute()}},shouldKill:function(){return this.tag?this.tag.checkTimedOut():this.checkTimedOut()},onError:function(){return this.tag?this.tag.SetTimedOut("error"):this.SetTimedOut("error")}},!this.async&&(b.client.canAccelerate(this.container)||(this.position===b.currentPosition||this.position>b.currentPosition&&this.movable)&&this.timeout===false))},
isRequiredScriptLoaded:function(a){b.load.poll(true);return this._requiredScriptsLoadResults[a]?true:false},getLoadTime:function(){var a=+new Date-this.startTime;return isNaN(a)?0:a}};b._tags=[];b.onDomReady(function(){b.doTags(b.position.DOM_COMPLETE)});b.blockTag=function(){var a=(s.location.protocol==="https:"?"https":"http")+"://{{waitservice}}/wait/{{delay}}/0/{{uid}}_{{id}}",d=b.POLL_INTERVAL;return function(e,f,g){function h(){var w=new Date-q,m=d-b.waitLatency<0?0:d-b.waitLatency;b.waitLatency=
w-m;g.logError("Blocked for "+w+" v "+m+" adjusting offset to "+b.waitLatency+" tag("+e+")","debug");b._waiting=false}if(g=b.getTag(e,f)){g.isReadyToExecute()&&g.canExecute()&&g.execute();if(g.hasExecuted()||g.checkTimedOut()||!b.client.canWait())b._doTagsCallback=true;else{var i=d-b.waitLatency<0?0:d-b.waitLatency,k=L.to_html(a,{delay:i,uid:b.num.getCacheBuster(5),id:e,waitservice:g.container.waitService}),o=L.to_html('(function () { TMAN.syncSafe=true; var Tag = TMAN.getTag(\'{{id}}\', "{{account}}"); if (!Tag.isReadyToExecute() && !Tag.checkTimedOut() ) { Tag.logError("blocking page for tag (id: {{id}}), elapsed " + Tag.getElapsed(),"debug");TMAN.blockTag(\'{{id}}\', "{{account}}");}else {Tag.logError("executing tag id: {{id}}","debug");TMAN.doTags(TMAN.currentPosition,false);TMAN.syncSafe=false;} })();',
{id:e,account:f}),q=+new Date;b.load.poll();if(b._waiting)g.logError("Not blocking for Tag + "+g.id+" due to TMAN._waiting. Tag will only be executed by doTags callback in this version which can cause issues with more than 2 accelerated tags at the same position","warning");else{g.starttimeoutTimer();g.setStartTime();if(g.container.blockCalls++>b.MAX_BLOCK_CALLS){b.getContainerByName(f).log.error("MAX_BLOCK_CALLS ("+g.container.MAX_BLOCK_CALLS+") reached for "+f+" whilst blocking for tag "+e,"fatal");
return false}g.logError("Blocking for tag ("+e+") with delayWithLatencyAdjusted: "+i+", elapsed "+g.getElapsed(),"debug");b._waiting=true;b.util.writeScript(k,false,{timeout:d,shouldKill:function(){return g.isTimedOut()},onLoad:h});b.hack.addDelayedWrite(o)}}}else b.util.log("Unable to find tag for blocking ("+e+","+f+")","error")}}();b.getTag=function(a,d){var e;e=d?b.getContainerByName(d):b._containers[0];if(!e||!(e instanceof b.Container)){b.util.log("Container "+d+" does not exist. Can't get tag.",
"error");return false}e=e.getTagById(a);if(!e||!(e instanceof b.Tag)){b.util.log("Tag (id: "+a+") does not exist on this container ("+d+").","error");return false}return e};b.getTagByReference=function(a,d){var e;e=d?b.getContainerByName(d):b._containers[0];if(!e||!(e instanceof b.Container)){b.util.log("Container "+d+" does not exist. Can't search tags.","error");return false}for(var f=e.tags.length;f&&f--;)if(e.tags[f].reference==a)return e.tags[f];return false};b.findTags=function(a,d){a=a.toLowerCase();
var e,f=[];if(b._containers.length===0){b.util.log("No containers "+d+" found. Can't search tags.","info");return false}for(var g=b._containers.length;g&&g--;){e=b._containers[g];if(!d||d==e.account)for(var h=e.tags.length;h&&h--;)(e.tags[h].code+"###"+e.tags[h].requiredScripts.join("###").toLowerCase()).indexOf(a)>-1&&f.push(e.tags[h])}return f};b.tagsExecuted=function(a,d){var e=[];if(b._containers.length===0){b.util.log("No containers "+d+" found. Can't search tags.","info");return false}for(var f=
b._containers.length;f&&f--;){c=b._containers[f];if(!d||d==c.account)for(var g=c.tags.length;g&&g--;){var h=c.tags[g];if((typeof a==="undefined"||a===true)&&h.getExecutedAt()>=0||a===false&&(!h.hasExecuted()||h.getExecutedAt()<0)||h.hasExecuted()&&h.getExecutedAt()===a)e.push(h)}}return e};b.addTag=function(a,d){if(d instanceof b.Tag){b.util.log("TMAN.addTag has changed, no longer accepts Tag","fatal");return false}var e=new b.Tag(a,d);if(e instanceof b.Tag){b.addTags(e);return true}else return false};
b.addTags=function(){if(!b._containers||!(b._containers[0]instanceof b.Container)){b.util.log("no container to add tag to","warning");return false}return b.Container.prototype.addTags.apply(b._containers[0],arguments)};j.TMAN=j.TMAN||{};b.client=function(){function a(i){f=p;var k=(i||navigator.userAgent).toLowerCase();if(k.indexOf("opera")>-1){if(i=k.match(/\bversion[\s\/](\d+\.\d+)/))f=i[1];else if(i=k.match(/\bopera[\s\/](\d+\.\d+)/))f=i[1];e="OP"}else if(k.indexOf("msie")!=-1){e="IE";if(i=k.match(/\bmsie (\d+\.\d+)/))f=
parseFloat(i[1])}else if(k.indexOf("firefox")!=-1){e="FF";if(i=k.match(/\bfirefox\/(\d+\.\d+)/))f=i[1]}else if(k.indexOf("chrome")>-1){e="CR";if(i=k.match(/\bchrome\/(\d+\.\d+)/))f=i[1]}else if(k.indexOf("safari 1.1.3")>-1||k.indexOf("safari/525.27.1")>-1||k.indexOf("applewebkit ")>-1){f="0.0";e="SF"}else if(k.indexOf("applewebkit")>-1){if((i=k.match(/\bversion\/(\d+\.\d+)/))&&k.indexOf("safari/534.8")==-1)f=i[1];else if(i=k.match(/\bapplewebkit\/(\d+\.?\d+)/)){k={"419":"2.0","418.9":"2.0","418.8":"2.0",
"418":"2.0","417.9":"2.0","416.11":"2.0","416.12":"2.0","412.17":"2.0","412.6":"2.0","412":"2.0","312.8":"1.3","312.5":"1.3","312.1":"1.3","125.4":"1.2","125.5":"1.2","125.2":"1.2","124":"1.2","85.8":"1.0","85.7":"1.0"};f=typeof k[i[1]]!="undefined"?k[i[1]]:"0.0"}e="SF"}else{e="OT";return false}return true}function d(i){h=p;i=i||navigator.userAgent;i=i.toLowerCase();if(i.indexOf("windows ca")!=-1)g="WMB";else if(i.indexOf("windows")!=-1)g="WIN";else if(i.indexOf("ipad")!=-1)g="IPA";else if(i.indexOf("ipod")!=
-1)g="IPO";else if(i.indexOf("iphone")!=-1)g="IPH";else if(i.indexOf("macintosh")!=-1)g="MAC";else if(i.indexOf("symbian")!=-1)g="SYM";else if(i.indexOf("android")!=-1)g="AND";else if(i.indexOf("linux")!=-1)g="LIN";else{g="OTH";return false}return true}var e,f,g,h;a();d();return{identify:function(i){return a(i)&&d(i)},getBrowserName:function(){return e},getBrowserVersion:function(){return f*1},getBrowser:function(){return e+(f||"")},getOSName:function(){return g},getOS:function(){return g+(h||"")},
canKill:function(){return e!="IE"},canAsyncJS:function(){return!(e=="OP"||e=="IE"&&f<10||e=="FF"&&f<3.6)},canDeferJS:function(){return e=="IE"||e=="SF"&&f>=4},canKillSyncJS:function(){return false},canPrecache:function(){return!(e==="IE"&&f<=7)},preCacheType:function(){return e==="OP"||e==="CR"||e==="IE"||e==="SF"?"image":"object"},useDelayedWrite:function(){return e==="IE"&&f>=7},useReadyState:function(){return e==="IE"},canWait:function(){return b.waitLatency!==false&&(e!="IE"||f>=7)},canAccelerate:function(i){return(i&&
i instanceof b.Container?i.tagAcceleration||false:true)&&this.inWhitelist()},inWhitelist:function(){return e==="IE"&&f>=7&&f<=9||e==="FF"&&f>=3||e==="CR"&&f>=6},isBodyAppendSafe:function(){return e!="IE"},dataReplacement:function(){if(e=="FF")return"about:blank";return null},srcReplacement:function(i){b.util.log("srcReplacement("+e+") - "+i.nodeName+" / parent = "+i.parentNode.nodeName,"debug");return e=="FF"||e=="IE"&&f>=9?"about:blank":e=="IE"?i.nodeName=="IMG"?!i.parentNode.removeChild(i):false:
null},textReplacement:function(){if(e=="FF")return"about:blank";return null},isExecSafeOnload:function(){return false}}}();var M=b,I;a:switch(b.client.getOS()){case "WIN":case "MAC":case "LIN":I=50;break a;default:I=100}M.POLL_INTERVAL=I;b.Rule=function(a){if(typeof a!="object")throw Error("`options` required for TMAN.Rule");this.likeOR=a.likeOR||[];if(typeof this.likeOR!="object")this.likeOR=[this.likeOR];this.likeAND=a.likeAND||[];if(typeof this.likeOR!="object")this.likeAND=[this.likeAND];this.equals=
a.equals||[];if(typeof this.equals!="object")this.equals=[this.equals];this.greaterThan=typeof a.greaterThan!="undefined"?a.greaterThan:false;this.lessThan=typeof a.lessThan!="undefined"?a.lessThan:false;this.reverseMatch=a.reverseMatch||false};b.Rule.prototype={test:function(a){var d;if(a===null||typeof a=="undefined")b.util.log("`subject` required for TMAN.Rule","error");else{if(this.greaterThan&&a<=this.greaterThan||this.lessThan&&a>=this.lessThan)return this.reverseMatch?true:false;var e=this.equals.length;
if(e){for(d=false;e--;)if(a==this.equals[e])d=true;if(!d)return this.reverseMatch?true:false}var f=[this.likeOR,this.likeAND],g=2;for(a=a.toString();g--;)if(e=f[g].length){for(d=false;e--;)if(a.indexOf(f[g][e])>-1)d=true;else if(g===1)return this.reverseMatch?true:false;if(!d)return this.reverseMatch?true:false}return this.reverseMatch?false:true}}};b.MAX_URL_LENGTH=2E3;b.CONVERSION_PARAMETERS=["levrev","levresdes","levordref"];b.Track=function(a,d){if(a){if(!(a instanceof b.Container))throw Error("container must be a TMAN.Container");
this._container=a;this._container.track=this}d||(d={});this.setOptions(d)};b.Track.prototype={setOptions:function(a){for(var d=false,e=["callback","campaignEvent","clientname","sessionTimeout","testMode"],f,g=0;f=e[g++];)if(typeof this[f]=="undefined"&&a[f]!="undefined"){this["_"+f]=a[f];d=true}if(typeof this._campaignEvent!=="undefined"){if(!(this._campaignEvent instanceof b.CampaignEvent))throw Error("campaignEvent must be a TMAN.CampaignEvent");}else this._campaignEvent=new b.CampaignEvent;if(this._container){if(typeof this._container.account!==
"undefined")this._clientname=this._container.account;if(typeof this._container.sessionTimeout!=="undefined")this._sessionTimeout=this._container.sessionTimeout}if(typeof this._sessionTimeout==="undefined")this._sessionTimeout=1800;if(!this._clientname)throw Error("must have a clientname (either in options, or from container.account");this.session=new b.Session(this._clientname,this._sessionTimeout);return d},getCampaignEvent:function(){return this._campaignEvent},setReferrer:function(a){this._campaignEvent.setReferrer(a)},
getReferrer:function(){return this._campaignEvent.getReferrer()},getLocation:function(){return this._campaignEvent.getLocation()},setLocation:function(a){this._campaignEvent.setLocation(a)},setParamsFromQueryString:function(){var a=this._campaignEvent.getLocationParams();return this._campaignEvent.setOptions({campaignId:a.tmcampid,placementRef:a.tmplaceref,clickRef:a.tmclickref,eventType:a.tmad==="i"?b.CampaignEvent.VIEW:a.tmad==="c"?b.CampaignEvent.CLICK:p})},gettmParams:function(){tmParam=j.tmParam;
if(typeof tmParam==="undefined")return false;var a={campaignId:tmParam.tmcampid,placementRef:tmParam.tmplaceref,clickRef:tmParam.tmclickref,eventType:tmParam.tmad==="i"?b.CampaignEvent.VIEW:tmParam.tmad==="c"?b.CampaignEvent.CLICK:p};this._custom=tmParam.tmcustom;for(var d=0;key=b.CONVERSION_PARAMETERS[d++];)if(typeof tmParam[key]!=="undefined"){this["_"+key]=tmParam[key];this._isConversion=true}return this._campaignEvent.setOptions(a)},_getContainerParam:function(a){if(!this._container)throw Error("can't call getContainerParams if you haven't passed a container in the constructor");
a=b.getParam(a,this._container);if(a=="")return p;return a},getContainerParams:function(){if(!this._container)throw Error("can't call getContainerParams if you haven't passed a container in the constructor");var a=this._getContainerParam("tmad");a=a==="i"?b.CampaignEvent.VIEW:a==="c"?b.CampaignEvent.CLICK:p;a={campaignId:this._getContainerParam("tmcampid"),placementRef:this._getContainerParam("tmplaceref"),clickRef:this._getContainerParam("tmclickref"),eventType:a};this._custom=this._getContainerParam("tmcustom");
for(var d=0;key=b.CONVERSION_PARAMETERS[d++];){var e=this._getContainerParam(key);if(typeof e!=="undefined"){this["_"+key]=e;this._isConversion=true}}return this._campaignEvent.setOptions(a)},_setHistory:function(a){var d=false,e=this.getHistory(b.CampaignEvent.CLICK);if(e){a.tmch=e;d=true}if(e=this.getHistory(b.CampaignEvent.VIEW)){a.tmvh=e;d=true}return d},settmParams:function(){var a=j.tmParam;if(typeof a==="undefined"){b.util.log("no window.tmParam object","error");return false}var d=false;if(this._campaignEvent.campaignId){a.tmcampid=
this._campaignEvent.campaignId;a.tmad=this._campaignEvent.eventType===b.Track.VIEW?"i":"c";if(this._campaignEvent.placementRef)a.tmplaceref=this._campaignEvent.placementRef;if(this._campaignEvent.clickRef)a.tmclickref=this._campaignEvent.clickRef;d=true}return d=d||this._setHistory(a)},setContainerParams:function(){if(!this._container)throw Error("can't call setContainerParams if you haven't passed a container in the constructor");var a=false;if(this._campaignEvent.campaignId){var d={tmcampid:this._campaignEvent.campaignId,
tmad:this._campaignEvent.eventType===b.Track.VIEW?"i":"c"};if(this._campaignEvent.placementRef)d.tmplaceref=this._campaignEvent.placementRef;if(this._campaignEvent.clickRef)d.tmclickref=this._campaignEvent.clickRef;a=true}(a=a||this._setHistory(d))&&this._container.addParams(d);return a},isConversion:function(){return this._isConversion},getConversionParams:function(){var a,d=0,e;for(e={};a=b.CONVERSION_PARAMETERS[d++];)if(typeof this["_"+a]!=="undefined")e[a]=this["_"+a];return e},sessionActive:function(){if(this._testMode)return false;
if(typeof this._clientname==="undefined")return false;return this.session.isActive()},setBaseCampaignRule:function(a){if(!a.execute||typeof a.execute!=="function")throw Error("base rule does not have an execute method");return this.baseRule=a},callTrackingServer:function(a){if(this.serverCalled)return false;if(!(this._campaignEvent.campaignId||this._isConversion))return false;a=this.getTrackingServerURL(a);if(!a)return false;b.util.appendScript(a.substring(0,b.MAX_URL_LENGTH),false);return this.serverCalled=
true},getTrackingServerURL:function(a){if(!a){if(!this._container)throw Error("can't call getTrackingServerURL if you haven't passed a container in the constructor");a=this._container.serverCall}if(!a){b.util.log("no serverCall specified for the current container","error");return false}var d="_callback"+(new Date).getTime();a=a+"?tracking=1";if(this._campaignEvent.campaignId){a+="&tmcampid="+this._campaignEvent.campaignId+"&tmad="+(this._campaignEvent.eventType===b.Track.VIEW?"i":"c");if(this._campaignEvent.placementRef)a+=
"&tmplaceref="+encodeURIComponent(this._campaignEvent.placementRef);if(this._campaignEvent.clickRef)a+="&tmclickref="+encodeURIComponent(this._campaignEvent.clickRef)}if(this._isConversion){a+="&"+b.String.objectToQuery(this.getConversionParams());var e=this.getHistory(b.CampaignEvent.CLICK);if(e)a+="&tmch="+encodeURIComponent(e);if(e=this.getHistory(b.CampaignEvent.VIEW))a+="&tmvh="+encodeURIComponent(e)}if(this._custom)a+="&tmcustom="+encodeURIComponent(this._custom);var f=this;b.Track[d]=function(g){f._callback&&
f._callback(g);f.trackingServerCalled=true;delete b.Track[d]};a+="&jsonp=TMAN.Track."+d;return a},applyCampaignRules:function(){if(this.sessionActive()||!this.baseRule)return false;return this.baseRule.execute(this._campaignEvent)},testCampaignRules:function(a){if(this.sessionActive()||!this.baseRule)return false;for(var d=new b.CampaignEvent,e=0;e<a.length;e++){var f=a[e];d.setReferrer(f.referrer);d.setLocation(f.location);if(!this.baseRule.execute(d)){this.reason="base rule failed";return false}for(var g in f.expected)if(f.expected[g]!==
d[g]){this.reason=f.name+" failed: value of "+g+" expected to be "+f.expected[g]+" but was "+d[g];return false}}return true},initialize:function(){this._isConversion=false;this.gettmParams();this._container&&this.getContainerParams();this.setParamsFromQueryString();this.applyCampaignRules();if(this._campaignEvent.campaignId){this.addEventToHistory();this.settmParams();this._container&&this.setContainerParams()}return this._campaignEvent.campaignId},tm2bootstrap:function(){this.initialize()},addEventToHistory:function(){if(!this._campaignEvent.campaignId)return false;
var a="his:"+this._campaignEvent.eventType+":"+this._clientname,d=b.storage.get(a)||"";if(d)d+=" ";d+=this._campaignEvent.serialize();b.storage.set(a,d,301536E3);return true},getHistory:function(a){return b.storage.get("his:"+a+":"+this._clientname)||false}};b.LandingPageRule=function(a){if(!a)throw Error("options required for TMAN.LandingPageRule");if(typeof a!="object")throw Error("options passed to TMAN.LandingPageRule is not an object");if(!a.campaignId)throw Error("No campaignId specified for call to TMAN.LandingPageRule");
this.campaignId=a.campaignId;if(!a.match)throw Error("No match function specified for call to TMAN.LandingPageRule");this.match=a.match;if(!a.rulePriority)a.rulePriority=1;this.rulePriority=a.rulePriority;this.match=a.match;this.clickRef=a.clickRef;this.placementRef=a.placementRef;this.subrules=[]};b.LandingPageRule.prototype={addCampaignRule:function(a){if(!(a instanceof b.LandingPageRule))throw Error("rule argument must be a TMAN.LandingPageRule object");this.subrules.push(a);this.subrules.length>
1&&this.subrules.sort(function(d,e){return e.rulePriority-d.rulePriority});return a},execute:function(a){if(!(a instanceof b.CampaignEvent))throw Error("argument to execute needs to be a TMAN.CampaignEvent");var d=this.match(a);if(!d)return false;d=typeof d==="object"?d:{};var e=d.campaignId||this.campaignId;if(e)a.campaignId=e;if(e=d.placementRef||this.placementRef)a.placementRef=e;if(e=d.clickRef||this.clickRef)a.clickRef=e;if(d=d.viewEvent||this.viewEvent)a.viewEvent=d;for(d=0;d<this.subrules.length;d++)if(this.subrules[d].execute(a))break;
return true}};var z=["facebook","linkedin","bebo","twitter","orkut","friendster","livejournal","blogspot","wordpress","friendfeed","myspace","digg","reddit","stumbleupon","twine","yelp","mixx","delicious","tumblr","disqus","intensedebate","plurk","slideshare","backtype","netvibes","mister-wong","diigo","flixster","youtube","vimeo","12seconds","zooomr","identi","jaiku","flickr","imeem","dailymotion","photobucket","fotolog","smugmug","classmates","myyearbook","mylife","tagged","brightkite","ning","hi5",
"yuku","cafemom","xanga","soundcloud","asmallworld","badoo","bigdadda","biip","blogster","buzznet","couchsurfing","cross","cyworld","focus","fotolog","foursquare","gather","geni","hyves","itsmy","kiwibox","lunarstorm","mixi","mocospace","multiply","myheritage","myopera","netlog","opendiary","plaxo","quora","qzone","renren","ryze","skyrock","socialvibe","sonico","travbuddy","trombi","viadeo","wayn","xanga","xing"];b.LandingPageRule.matchSocial=function(a,d){var e=a.getReferrerDomain(),f=z.slice(0);
d&&f.push(d);f="\\.("+f.join("|")+")\\.";return e.match(RegExp(f))};var H=["google","yahoo","msn","bing","aol","lycos","ask","altavista","netscape","cnn","looksmart","about","mamma","alltheweb","gigablast","voila","virgilio","live","baidu","alice","yandex","najdi","club-internet","mama","seznam","search","szukaj","netsprint","google.interia","szukacz","yam","pchome","search.conduit","search.bt","search.mywebsearch","search.virginmedia","search.sky","uk.search-results","aolsearch.aol","search.alot",
"search.orange","search.aol","uk.search.yahoo","search.babylon","search.aol","blekko","chacha","naver","nate","duckduckgo","entireweb","faroo","info","go","hakia","leapfish","monstercrawler","dmoz","rambler","omgili","spezify","webcrawler","teoma","dogpile","excite","hotbot","genieknows","vivisimo","a9","goodsearch","guruji","yummly","goby"];b.LandingPageRule.matchSEO=function(a,d){var e=a.getReferrerDomain(),f=H.slice(0);d&&f.push(d);f="\\.("+f.join("|")+")\\.";return e.match(RegExp(f))?{placementRef:e,
clickRef:a.getReferrerKeywords()}:false};b.LandingPageRule.matchSecureSEO=function(a){var d=a.getReferrerDomain();if(!d.match(/\.(google)\./))return false;a=a.getReferrerParams().esrc;if(!a)return false;if(a!=="s")return false;return{placementRef:d}};b.LandingPageRule.Test=function(a){if(!a)throw Error("options required for TMAN.LandingPageRule.Test");if(typeof a!="object")throw Error("options passed to TMAN.LandingPageRule.Test is not an object");if(!a.expected)throw Error("No expected specified for call to TMAN.LandingPageRule.Test");
if(typeof a.expected!="object")throw Error("expected is not an object");this.expected=a.expected;if(!a.name)throw Error("No name specified for call to TMAN.LandingPageRule.Test");this.referrer=a.referrer;this.location=a.location;this.name=a.name};b.CampaignEvent=function(a){a||(a={});this.setOptions(a);this.referrer=s.referrer;this.location=s.location.toString()};b.CampaignEvent.CLICK=0;b.CampaignEvent.VIEW=1;b.CampaignEvent.prototype={setOptions:function(a){for(var d=false,e=["campaignId","placementRef",
"clickRef","eventType"],f,g=0;f=e[g++];)if(typeof a[f]!=="undefined"){this[f]=a[f];d=true}if(typeof this.eventType==="undefined")this.eventType=b.CampaignEvent.CLICK;return d},setReferrer:function(a){this.referrer=a},getReferrer:function(){return this.referrer},setLocation:function(a){this.location=a},getLocation:function(){return this.location},getReferrerParams:function(a){a=a||this.referrer;if(!a)return{};a=a.split("?");if(!a.length==2)return{};return b.String.queryToObject(a[1])},getLocationParams:function(a){a=
a||this.location;if(!a)return{};a=a.split("?");if(!a.length==2)return{};return b.String.queryToObject(a[1])},getReferrerKeywords:function(a){a=a||this.referrer;if(a=/[?&](q|p|query|encquery|terms|rdata|szukaj|k|qt|qs|wd|text)=([^&]*)/.exec(a))return decodeURIComponent(a[2].replace(/\+/g," "));return""},getReferrerDomain:function(a){return(a=a||this.referrer)?a.replace(/^https?:\/\/([^\/]+)\/.*$/,"$1"):""},serialize:function(){var a=new Date;a=parseInt((a.getTime()+a.getTimezoneOffset()*6E4)/1E3,10);
return[a,this.campaignId,b.util.scramble(this.placementRef||""),b.util.scramble(this.clickRef||"")].join(";")}};LEVU={};LEVU.ABoH=b.util.append;LEVU.AIF=b.util.appendIframe;LEVU.GPR=b.util.getProtocol;LEVU.GP=b.String.getParam;LEVU.SP=b.String.setParam;LEVU.OTQ=b.String.objectToQuery;LEVU.QTO=b.String.queryToObject;LEVU.RX=b.String.regEx;LEVU.SS=b.String.subString;LEVU.FD=b.String.isFound;LEVU.GS=b.String.getStem;LEVU.PR=b.String.printR;LEVU.LES=b.String.lescape;LEVU.DLE=b.String.doubleLescape;LEVU.WIF=
b.util.writeIframe;LEVU.AJS=b.util.appendScript;LEVU.CIm=b.util.createImage;LEVU.LE=b.util.log;LEVU.IIF=b.util.isInIframe;LEVU.WJS=b.util.writeJS;LEVU.PKV=b.util.parseKeyValue;LEVU.SKV=b.util.setKeyValue;LEVU.ES=b.hack.evalScript;LEVU.SQ=b.hack.getScriptParams;LEVU.FS=b.hack.findScript;LEVU.ADW=b.hack.addDelayedWrite;LEVU.IDW=b.hack.initDelayedWrite;LEVU.WDW=b.hack.writeDelayedWrite;LEVU.DS=b.num.doSample;LEVU.GetCB=b.num.getCacheBuster;LEVU.GC=function(a){return b.util.cookie(a)};LEVU.SC=function(a,
d,e,f){b.util.cookie(a,d,{path:e,expires:f})};try{LEVU.ES("lu.js");var G=LEVU.SQ("lu.js");G&&b.util.log("Querystring ["+G+"] found on lu.js, no longer supported","FATAL")}catch(J){b.util.log("Error excuting LEVU.SQ on bootStrap of lu.js","ERROR")}b.DOMQ=function(a){this.el=a||s};b.DOMQ.factory=function(a){for(var d=[],e=0,f=a.length;e<f;e++)d[e]=new b.DOMQ(a[e]);return d};b.DOMQ.prototype={id:function(a){if(!this.el)return this;if(!this.el.getElementById)return s.getElementById(a);this.el=this.el.getElementById(a);
return this},tag:function(a,d){if(!this.el)return this;this.el=this.el.getElementsByTagName(a)[d||0];return this},name:function(a,d){if(!this.el)return this;this.el=this.getElementsByName(a)[d||0];return this},className:function(a,d){if(!this.el)return this;this.el=this.getElementsByClassName(a)[d||0];return this},isAncestor:function(a){var d=this.el;if(d){for(;a;){if(a==d&&a!=d)return true;a=a.parentNode}return false}},getElementsByName:function(a){if(!this.el)return[];a=s.getElementsByName(a);if(this.el===
s)return a;for(var d=[],e=0,f=a.length;e<f;e++)this.isAncestor(a[e])&&d.push(a[e]);return d},getElementsByClassName:function(a){if(!this.el)return[];var d=this.el.getElementsByTagName("*");a=a.replace(/\-/g,"\\-");a=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");for(var e=[],f=0,g=d.length;f<g;f++)a.test(d[f].className)&&e.push(d[f]);return e},match:function(a,d){return(new b.String(this.toString())).match(a,d)},replace:function(a,d){return(new b.String(this.toString())).replace(a,d)},toString:function(){if(!this.el)return"";
return this.el==s?this.el.documentElement.innerHTML:this.el.value?this.el.value:this.el.innerHTML}};b.DT=function(){var a={html:function(){return new b.DOMQ},id:function(e){return a._html.id(e)},tag:function(e,f){return a._html.tag(e,f)},name:function(e,f){return a._html.name(e,f)},className:function(e,f){return a._html.className(e,f)},head:function(){return a.tag("head")},body:function(){return a.tag("body")}};a._html=a.html();var d=function(e){for(var f in e){var g=e[f],h="";if(typeof g=="string")h=
a.id(g);else if(g instanceof RegExp)h=a.html().match(g,"$1");else if(g instanceof Array)h=a.id(g[0]).match(g[1],"$1");else if(typeof g=="function")h=g(a)||"";b.conf.param[f]=""+h}};j.LEV_DT&&d(j.LEV_DT);return d}()})(this);this.LEV=this.LEV||{};this.Lescape=TMAN.String.escape;this.DoubleLescape=TMAN.String.doubleEscape;if(!LEV.extend)LEV.extend=TMAN.util.extend;if(!LEV.String)LEV.String=TMAN.String;if(!LEV.StringBuilder)LEV.StringBuilder=TMAN.StringBuilder;if(!LEV.DOMQ)LEV.DOMQ=TMAN.DOMQ;
if(!LEV.DT)LEV.DT=TMAN.DT;if(!LEV.onDOM)LEV.onDOM=TMAN.onDomReady;LEV.checkURLTracking=function(){var j=document.location.search||"";if(j){var p=TMAN.String.getParam(j.substr(1),"tmcampid");p&&TMAN.util.extend(TMAN.conf.param,{tmcampid:p,tmad:TMAN.String.getParam(j,"tmad"),tmplaceref:TMAN.String.getParam(j,"tmplaceref"),tmclickref:TMAN.String.getParam(j,"tmclickref")})}};
LEV.bootStrap=function(){TMAN.conf.id=window.tmPageId;if(TMAN.conf.landingPageMins&&TMAN.SessionCookie.isActive(TMAN.conf.landingPageMins)){TMAN.util.log("Session cookie still active and tmOPV set to ["+TMAN.conf.landingPageMins+"] minutes","MESSAGE");return false}else if(TMAN.conf._lastContainerId==TMAN.conf.id)return false;else{TMAN.conf._tagStr="";TMAN.conf._tagStr=TMAN.util.cookie("tmStaging")?TMAN.conf.baseURL.replace(/(.*?)\/\/(.*?)\.(.*)/,"$1//tagstaging.$3"):TMAN.conf.baseURL;TMAN.conf._tagStr=
TMAN.conf._tagStr+"/tmpageid="+TMAN.conf.id;TMAN.conf.lastContainerId=TMAN.conf.id;TMAN.conf._tagStr+="&levyouruid="+Math.random();TMAN.conf._tagStr+="&tmsecmode="+(TMAN._secure?"S":"N");TMAN.conf.enableURLTracking&&LEV.checkURLTracking();var j=TMAN.conf._tagStr+LEV_TMIFPS();if(TMAN.conf.param&&(TMAN.conf.param.tmcampid||TMAN.conf.param.levrev||TMAN.conf.param.levresdes)){window.tmCBRequired=true;TMAN.conf._callbackRequired=true}j=j+"&tmtag=js";if(TMAN.conf.enableJSCall)if(window.tm2BootAsync)TMAN.util.appendScript(j,
false,{defer:false});else TMAN.syncSafe?TMAN.util.writeScript(j):TMAN.util.log("Unable to initiliaze container, !syncSafe && !tm2BootAsync","fatal")}};function LEV_TMIFPS(){var j=new LEV.StringBuilder;if(typeof TMAN.conf.param!="undefined")for(var p in TMAN.conf.param){var n=TMAN.conf.param[p],r=typeof n;if(r==="function"){n=n();r=typeof n}if(p&&n&&(r=="number"||r=="string"||r=="boolean"))j.append("&",p,"=",TMAN.String.doubleEscape(n))}return j.toString()}
function LEV_TMTCB(){window.tmTrack=undefined;window.tmTrackWaiting&&LEV_TMIFCB()}
var LEV_TMIFCB=function(){function j(){window.LEV_DT&&LEV.DT(window.LEV_DT);if(window.LEV_DTD)for(var r=0;r<LEV_DTD.length;r++)LEV_DTD[r]();n()}function p(r){r=TMAN.conf._tagStr+LEV_TMIFPS()+(typeof TMAN.conf.tmbtpos==="number"?"&tmbtpos="+TMAN.conf.tmbtpos:"")+(r?"&tmtag="+r:"");TMAN.util.log("URL for callback: "+r,"DEBUG");return r}function n(){if(typeof window.tmDisableIframe!="undefined")TMAN.conf._disableIframe=window.tmDisableIframe;if(typeof window.tmCBRequired!="undefined")TMAN.conf._callbackRequired=
window.tmCBRequired;if(location.hash=="#tmtest")parent.location=document.referrer+"#"+p();try{TMAN.util.log("referrer="+document.referrer,"DEBUG");if(typeof TMAN.conf.param=="object"){var r="",B;for(B in TMAN.conf.param)if(typeof TMAN.conf.param[B]!="undefined")r+="\t"+B+"=>"+TMAN.conf.param[B]+"\n";r||(r="<empty>")}TMAN.util.log("TMAN.conf.param contents\n"+r,"DEBUG");typeof tmOPV!="undefined"&&TMAN.util.log("tmOPV="+TMAN.conf.landingPageMins,"DEBUG");TMAN.util.log("tmBaseURL="+TMAN.conf.baseUrl,
"DEBUG");TMAN.util.log("tmPageId="+TMAN.conf.id,"DEBUG")}catch(s){TMAN.util.log("logging error on of tmPageId or tmBaseURL probably does not exits"+s.message,"FATAL")}if(TMAN.conf._disableIframe){if(TMAN.conf.param&&(TMAN.conf.param.tmad||TMAN.conf.param.levrev||TMAN.conf.param.levresdes||TMAN.conf.param.levordref)||TMAN.conf._callbackRequired)if(LEV.onDOM.isReady()){r=p("image");TMAN.util.appendImage(r);TMAN.util.log("Image written: "+r)}else LEV.onDOM(function(){var C=p("image");TMAN.util.appendImage(C);
TMAN.util.log("Image written: "+C,"DEBUG")})}else if(LEV.onDOM.isReady()){r=p("iframe");TMAN.util.appendIframe(r);TMAN.util.log("Iframe written: "+r,"DEBUG")}else LEV.onDOM(function(){var C=p("iframe");TMAN.util.appendIframe(C);TMAN.util.log("Iframe written: "+C,"DEBUG")})}return function(){TMAN.conf._writeImmediately=window.tmImmediate||false;if(typeof TMAN!="undefined"&&typeof TMAN.doTags==="function"){TMAN.conf.tmbtpos=TMAN.currentPosition;j();TMAN.doTags(TMAN.currentPosition,window.tm2BootAsync)}else TMAN.conf._writeImmediately?
j():LEV.onDOM(j)}}();if(typeof TMAN.conf==="undefined"){TMAN.conf={param:{}};if(typeof tmPageId==="undefined")if(typeof tmContId==="undefined")TMAN.util.log("tmContId or tmPageId not defined for TagMan container, it's compulsary","FATAL");else tmPageId=tmContId}TMAN.util.extend(TMAN.conf,{_lastContainerId:0,_tagStr:"",_callbackRequired:false,_disableIframe:false,enableJSCall:true,enableURLTracking:true,_writeImmediately:false});TMAN.position=TMAN.position||{};
TMAN.util.extend(TMAN.position,{PRE_HEAD:0,TOP_HEAD:1,BOTTOM_HEAD:2,TOP_BODY:3,BOTTOM_BODY:31,DOM_COMPLETE:32,WINDOW_LOADED:33,END:64});if(typeof tmBaseUrl==="string"){TMAN.util.extend(TMAN.conf,{baseURL:window.tmBaseUrl,id:window.tmPageId,landingPageMins:window.tmOPV||false,bootstrap:typeof tmBootStrap==="undefined"?true:window.tmBootStrap,param:window.tmParam||{}});TMAN.conf.bootstrap&&LEV.bootStrap()}
TMAN.doTags=TMAN.doTags||function(j){var p=window.TMAN;if(j>=(typeof(window.tm2BootPosition!="undefined")?window.tm2BootPosition:p.position.TOP_BODY)&&typeof p.conf.TM2initialised==="boolean")if(!p.conf.TM2initialised){p.conf.TM2initialised=true;LEV.bootStrap()}};
TMAN.tm2initialise=function(j){TMAN.conf.param=TMAN.conf.param||{};if(j.baseURL||j.host&&j.account){window.TMAN.conf.baseURL=j.baseURL||(location.protocol==="https:"?"https://":"http://")+j.host+"/"+j.account+"/"+(j.serverCall||"tman.cgi");window.TMAN.conf.TM2initialised=j.bootstrap?false:true;if(typeof window.TMAN.Tag==="function")TMAN.getContainerByName(j.account).addTags(new TMAN.Tag("TMAN.conf.account=TMAN._containers[0].account;TMAN.conf.id=TMAN._containers[0].id;TMAN.conf.param=TMAN._containers[0].param;window.TMAN.conf.TM2initialised=true; LEV.bootStrap();",
{position:typeof window.tm2BootPosition!="undefined"?window.tm2BootPosition:TMAN.position.TOP_BODY,async:window.tm2BootAsync||false,movable:true,bootstrapper:true}))}else{TMAN.util.log("Problem with container code conf.baseURL and host/account not available","FATAL");TMAN.conf.TM2initialised=true}};
if(typeof TMAN.Container!=="function")TMAN.Container=function(j,p,n){var r=window.TMAN.conf;r.account=j||r.account;r.id=p||r.id;r.host=n.host||DEFAULT_HOST;r.tags=n.tags||[];r.async="async"in n?n.async:false;r.tagsBlockingTimeout=n.tagsBlockingTimeout||0;r.sessionTimeout=n.sessionTimeOut||3600;r.landingPageConteiner=n.landingPageContainer||false;r.bootstrap="bootstrap"in n?n.bootstrap:true;r.enableJSCall="enableJSCall"in n?n.enableJSCall:true;r.param=r.param||{};r.serverCall=n.serverCall||r.serverCall||
"tman.cgi/";TMAN.addContainer=TMAN.addContainer||function(){return true};TMAN.tm2initialise(TMAN.container)};TMAN.addContainer=TMAN.addContainer||function(){return true};if(typeof window.TMAN.asyncLoader==="function"){window.TMAN.asyncLoader();window.TMAN.asyncLoader=undefined}this.TMAN=this.TMAN||{};TMAN.MAP=function(){this.maps=[]};
TMAN.MAP.prototype={addMap:function(j){j=new TMAN.MAP.HashMap(j);this.maps[j.head.ParentCId()]=j},addMapIf:function(j,p){var n=new TMAN.MAP.HashMap(p);if(n.head.ParentCId()==j)this.maps[j]=n},search:function(j){j=TMAN.MAP.B92SHA1(j);var p,n;for(n in this.maps)if(p=this.maps[n])return p.Search(j)}};
TMAN.MAP.Head=function(j){var p;this.ok=true;this.error="";if(!(!j||j.length==0)){this.v=TMAN.B92.desmall(j.substr(0,2));if(this.v!=2){this.ok=false;this.error="Version "+this.v+" is unsupported"}else{this.hlen=TMAN.B92.desmall(j.substr(2,1));this.clen=TMAN.B92.desmall(j.substr(3,1));this.cid=TMAN.B92.desmall(j.substr(4,2));this.olen=TMAN.B92.desmall(j.substr(6,1));this.oto=TMAN.B92.desmall(j.substr(7,2));p=TMAN.B92.desmall(j.substr(9,1));this.schema=j.substr(10,p);this.maps=j.substr(10+p)}}};
TMAN.MAP.Head.prototype={Version:function(){return this.v},HashLen:function(){return this.hlen},CIdLen:function(){return this.clen},ParentCId:function(){return this.cid},OtherLen:function(){return this.olen},Maps:function(){return this.maps},OPVTO:function(){return this.oto},Schema:function(){return this.schema}};
TMAN.MAP.SHA1=function(j){function p(d,e){return d<<e|d>>>32-e}var n,r,B,s=Array(80),C=1732584193,b=4023233417,L=2562383102,M=271733878,I=3285377520,z,H,G,J;z=j.length;var a=[];for(n=0;n<z-3;n+=4){r=j.charCodeAt(n)<<24|j.charCodeAt(n+1)<<16|j.charCodeAt(n+2)<<8|j.charCodeAt(n+3);a.push(r)}switch(z%4){case 0:n=2147483648;break;case 1:n=j.charCodeAt(z-1)<<24|8388608;break;case 2:n=j.charCodeAt(z-2)<<24|j.charCodeAt(z-1)<<16|32768;break;case 3:n=j.charCodeAt(z-3)<<24|j.charCodeAt(z-2)<<16|j.charCodeAt(z-
1)<<8|128}for(a.push(n);a.length%16!=14;)a.push(0);a.push(z>>>29);a.push(z<<3&4294967295);for(j=0;j<a.length;j+=16){for(n=0;n<16;n++)s[n]=a[j+n];for(n=16;n<80;n++)s[n]=p(s[n-3]^s[n-8]^s[n-14]^s[n-16],1);r=C;z=b;H=L;G=M;J=I;for(n=0;n<80;n++){B=s[n];B=n<20?p(r,5)+(z&H|~z&G)+J+B+1518500249&4294967295:n<40?p(r,5)+(z^H^G)+J+B+1859775393&4294967295:n<60?p(r,5)+(z&H|z&G|H&G)+J+B+2400959708&4294967295:p(r,5)+(z^H^G)+J+B+3395469782&4294967295;J=G;G=H;H=p(z,30);z=r;r=B}C=C+r&4294967295;b=b+z&4294967295;L=L+
H&4294967295;M=M+G&4294967295;I=I+J&4294967295}return[C,b,L,M,I]};TMAN.MAP.B92SHA1=function(j){return TMAN.B92.encode(TMAN.MAP.SHA1(j),25)};TMAN.MAP.Map=function(j,p){if(j&&p){this.head=p;this.hash=j.substr(0,p.HashLen());this.Cid=TMAN.B92.desmall(j.substr(p.HashLen(),p.CIdLen()));this.Other=TMAN.B92.desmall(j.substr(p.HashLen()+p.CIdLen(),p.OtherLen()))}};
TMAN.MAP.Map.prototype={Hash:function(){return this.hash},ContainerId:function(){return this.Cid},Header:function(){return this.head},OncePerVisit:function(){return(this.Other&1)==1?true:false}};TMAN.MAP.HashMap=function(j){this.text=j;this.head=new TMAN.MAP.Head(this.text)};TMAN.MAP.HashMap.prototype.Search=function(j){var p=this.head,n=p.HashLen(),r=n+p.CIdLen()+p.OtherLen();j=j.substr(j.length-n);n=p.Maps();for(var B=0;;){B=n.indexOf(j,0);if(0%r==0)return new TMAN.MAP.Map(n.substr(B,r),p)}};


TMAN.position.CUSTOM_1=34;
TMAN.position.CUSTOM_2=35;
TMAN.position.CUSTOM_3=36;
TMAN.position.CUSTOM_4=37;
TMAN.position.CUSTOM_5=38;
TMAN.position.SIGNUP=39;
TMAN.position.UNSUB=40;
TMAN.position.PRINT=41;
TMAN.position.SHARE=42;
TMAN.position.RSS=43;
TMAN.position.NEWSLETTER=44;
TMAN.position.DOWNLOAD=45;
TMAN.position.EXCEL=46;
TMAN.position.PDF=47;
TMAN.position.CONTACTS=48;
TMAN.position.SURVEY_START=49;
TMAN.position.SURVEY_COMPLETE=50;
TMAN.position.CHAT=51;
TMAN.position.COMMENTED=52;
TMAN.position.RATED=53;
TMAN.position.CARTADD=54;
TMAN.position.FB_LIKE=55;
TMAN.position.FB_FRIEND=56;
TMAN.position.FB_JOIN=57;
TMAN.position.FB_FIND=58;
TMAN.position.TW_FOLLOW=59;
TMAN.position.FUNNEL_A_1=60;
TMAN.position.FUNNEL_A_2=61;
TMAN.position.FUNNEL_A_3=62;
TMAN.position.FUNNEL_A_4=63;
TMAN.position.FUNNEL_A_5=65;
TMAN.position.FUNNEL_B_1=66;
TMAN.position.FUNNEL_B_2=67;
TMAN.position.FUNNEL_B_3=68;
TMAN.position.FUNNEL_B_4=69;
TMAN.position.FUNNEL_B_5=70;
TMAN.position.FUNNEL_C_1=71;
TMAN.position.FUNNEL_C_2=72;
TMAN.position.FUNNEL_C_3=73;
TMAN.position.FUNNEL_C_4=74;
TMAN.position.FUNNEL_C_5=75;
TMAN.position.EXIT_BUTTON=76;
TMAN.position.EXIT_BUTTON_RETAIL=77;
TMAN.position.EXIT_BUTTON_ONLINE=78;
TMAN.position.ADD_PARAMS=79;
(function () {
	var product_level = -1;

	function getParam(strVarName) {
		return TMAN.conf.param[strVarName];
	}

	function isParamDefined(strVarName) {
		return typeof TMAN.conf.param[strVarName] !== "undefined";
	}

	function isParamValid(strVarName) {
		return isParamDefined(strVarName) && TMAN.conf.param[strVarName] !== "";
	}

	function searchArray(needle, array) {
		var i = 0;
		var len = array.length;

		for (var i = 0; i < len; i++) {
			if (array[i] === needle) {
				return i;
			}
		}

		return -1;
	}

	var campaign_name_list = ["smartphones", "smart-phones", "Smart-phones", "mobile-phone"];
	var campaign_path_list = ["/index.php", "/in/galaxynote3/"];
	var microsite_path_list = ["/in/galaxynote3/acc.html", "/in/galaxynote3/color.html", "/in/galaxynote3/spec.html"];

	var product_levels = ["product_local_type", "product_local_sub_type", "product_local_codes"];

	TMAN.samsung = {};

	TMAN.samsung.isActiveCampaign = function () {
		return isParamDefined("product_local_type") && searchArray(getParam("product_local_type"), campaign_name_list) > -1;
	};

	TMAN.samsung.isCampaign = function () {
		return isParamDefined("product_local_group") && getParam("product_local_group") === "campaign";
	};

	TMAN.samsung.isHomepage = function () {
		return document.location.pathname === "/in/";
	};

	TMAN.samsung.isMicrosite = function () {
		return searchArray(document.location.pathname, microsite_path_list) > -1;
	};

	TMAN.samsung.isProduct = function () {
		if (product_level > -1) {
			return product_level;
		}

		var i;
		var len = product_levels.length;
		var product_lvl = 0;

		for (var i = 0; i < len; i++) {
			if (!isParamValid(product_levels[i])) {
				break;
			}

			product_lvl++;
		}

		product_level = product_lvl;
		return product_level;
	};

	TMAN.samsung.isProductDetail = function () {
		return this.isActiveCampaign() && this.isProduct() === 3;
	};

	TMAN.samsung.isRetailerClick = function () {
		return searchArray(document.location.pathname, campaign_path_list) > -1;
	};

	TMAN.samsung.getDescription = function () {
		var description = "";
		var number = 0;
		var product = 0;

		if (this.isHomepage()) {
			number = 1001;
			description = "Home_Page_View";
		} else if (this.isRetailerClick()) {
			number = 1006;
			description = "Campaign_Landing_Page_View";
		} else if (this.isMicrosite()) {
			number = 1009;
			description = "Microsite_Aux_Page_Views";
		} else if (this.isActiveCampaign()) {
			if (this.isCampaign()) {
				number = 1006;
				description = "Campaign_Landing_Page_View";			
			} else if ((product = this.isProduct()) > 0) {
				if (product == 1) {
					number = 1002;
					description = "Product_Type_Page_View";
				} else if (product == 2) {
					number = 1003;
					description = "Product_SubType_Page_View";
				} else if (product == 3) {
					number = 1004;
					description = "Product_Detail_Page_View";
				}
			}
		}

		if (number > 0) {
			return number.toString()+'_'+description;
		} else {
			throw "No description";
		}
	};
})();

// tm3 async bootstrap
TMAN.doTags(TMAN.currentPosition,true);
