(function(e){var u=function(n,v){var d=e.extend({},e.fn.nivoSlider.defaults,v),f={currentSlide:0,currentImage:"",totalSlides:0,randAnim:"",running:!1,paused:!1,stop:!1},g=e(n);g.data("nivo:vars",f);g.css("position","relative");g.addClass("nivoSlider");var l=g.children();l.each(function(){var c=e(this),h="";c.is("img")||(c.is("a")&&(c.addClass("nivo-imageLink"),h=c),c=c.find("img:first"));var b=c.width();0==b&&(b=c.attr("width"));var m=c.height();0==m&&(m=c.attr("height"));b>g.width()&&g.width(b);
m>g.height()&&g.height(m);""!=h&&h.css("display","none");c.css("display","none");f.totalSlides++});0<d.startSlide&&(d.startSlide>=f.totalSlides&&(d.startSlide=f.totalSlides-1),f.currentSlide=d.startSlide);e(l[f.currentSlide]).is("img")?f.currentImage=e(l[f.currentSlide]):f.currentImage=e(l[f.currentSlide]).find("img:first");e(l[f.currentSlide]).is("a")&&e(l[f.currentSlide]).css("display","block");g.css("background",'url("'+f.currentImage.attr("src")+'") no-repeat');var k=0;!d.manualAdvance&&1<l.length&&
(k=setInterval(function(){p(g,l,d,!1)},d.pauseTime));d.directionNav&&(g.append('<div class="nivo-directionNav"><a class="nivo-prevNav">'+d.prevText+'</a><a class="nivo-nextNav">'+d.nextText+"</a></div>"),d.directionNavHide&&(e(".nivo-directionNav",g).hide(),g.hover(function(){e(".nivo-directionNav",g).show()},function(){e(".nivo-directionNav",g).hide()})),e("a.nivo-prevNav",g).live("click",function(){if(f.running)return!1;clearInterval(k);k="";f.currentSlide-=2;p(g,l,d,"prev")}),e("a.nivo-nextNav",
g).live("click",function(){if(f.running)return!1;clearInterval(k);k="";p(g,l,d,"next")}));if(d.controlNav){var s=e('<div class="nivo-controlNav"></div>');g.append(s);for(var q=0;q<l.length;q++)if(d.controlNavThumbs){var r=l.eq(q);r.is("img")||(r=r.find("img:first"));d.controlNavThumbsFromRel?s.append('<a class="nivo-control" rel="'+q+'"><img src="'+r.attr("rel")+'" alt="" /></a>'):s.append('<a class="nivo-control" rel="'+q+'"><img src="'+r.attr("src").replace(d.controlNavThumbsSearch,d.controlNavThumbsReplace)+
'" alt="" /></a>')}else s.append('<a class="nivo-control" rel="'+q+'">'+(q+1)+"</a>");e(".nivo-controlNav a:eq("+f.currentSlide+")",g).addClass("active");e(".nivo-controlNav a",g).live("click",function(){if(f.running||e(this).hasClass("active"))return!1;clearInterval(k);k="";g.css("background",'url("'+f.currentImage.attr("src")+'") no-repeat');f.currentSlide=e(this).attr("rel")-1;p(g,l,d,"control")})}d.keyboardNav&&e(window).keypress(function(c){if("37"==c.keyCode){if(f.running)return!1;clearInterval(k);
k="";f.currentSlide-=2;p(g,l,d,"prev")}if("39"==c.keyCode){if(f.running)return!1;clearInterval(k);k="";p(g,l,d,"next")}});d.pauseOnHover&&g.hover(function(){f.paused=!0;clearInterval(k);k=""},function(){f.paused=!1;""!=k||d.manualAdvance||(k=setInterval(function(){p(g,l,d,!1)},d.pauseTime))});g.bind("nivo:animFinished",function(){f.running=!1;e(l).each(function(){e(this).is("a")&&e(this).css("display","none")});e(l[f.currentSlide]).is("a")&&e(l[f.currentSlide]).css("display","block");""!=k||f.paused||
d.manualAdvance||(k=setInterval(function(){p(g,l,d,!1)},d.pauseTime));d.afterChange.call(this)});var t=function(c,h,b){for(var m=0;m<h.slices;m++){var a=Math.round(c.width()/h.slices);m==h.slices-1?c.append(e('<div class="nivo-slice"></div>').css({left:a*m+"px",width:c.width()-a*m+"px",height:"0px",opacity:"0",background:'url("'+b.currentImage.attr("src")+'") no-repeat -'+(a+m*a-a)+"px 0%"})):c.append(e('<div class="nivo-slice"></div>').css({left:a*m+"px",width:a+"px",height:"0px",opacity:"0",background:'url("'+
b.currentImage.attr("src")+'") no-repeat -'+(a+m*a-a)+"px 0%"}))}},w=function(c,h,b){for(var m=Math.round(c.width()/h.boxCols),a=Math.round(c.height()/h.boxRows),f=0;f<h.boxRows;f++)for(var d=0;d<h.boxCols;d++)d==h.boxCols-1?c.append(e('<div class="nivo-box"></div>').css({opacity:0,left:m*d+"px",top:a*f+"px",width:c.width()-m*d+"px",height:a+"px",background:'url("'+b.currentImage.attr("src")+'") no-repeat -'+(m+d*m-m)+"px -"+(a+f*a-a)+"px"})):c.append(e('<div class="nivo-box"></div>').css({opacity:0,
left:m*d+"px",top:a*f+"px",width:m+"px",height:a+"px",background:'url("'+b.currentImage.attr("src")+'") no-repeat -'+(m+d*m-m)+"px -"+(a+f*a-a)+"px"}))},p=function(c,h,b,f){var a=c.data("nivo:vars");a&&a.currentSlide==a.totalSlides-1&&b.lastSlide.call(this);if((!a||a.stop)&&!f)return!1;b.beforeChange.call(this);f?("prev"==f&&c.css("background",'url("'+a.currentImage.attr("src")+'") no-repeat'),"next"==f&&c.css("background",'url("'+a.currentImage.attr("src")+'") no-repeat')):c.css("background",'url("'+
a.currentImage.attr("src")+'") no-repeat');a.currentSlide++;a.currentSlide==a.totalSlides&&(a.currentSlide=0,b.slideshowEnd.call(this));0>a.currentSlide&&(a.currentSlide=a.totalSlides-1);e(h[a.currentSlide]).is("img")?a.currentImage=e(h[a.currentSlide]):a.currentImage=e(h[a.currentSlide]).find("img:first");b.controlNav&&(e(".nivo-controlNav a",c).removeClass("active"),e(".nivo-controlNav a:eq("+a.currentSlide+")",c).addClass("active"));e(".nivo-slice",c).remove();e(".nivo-box",c).remove();"random"==
b.effect&&(h="sliceDownRight sliceDownLeft sliceUpRight sliceUpLeft sliceUpDown sliceUpDownLeft fold fade boxRandom boxRain boxRainReverse boxRainGrow boxRainGrowReverse".split(" "),a.randAnim=h[Math.floor(Math.random()*(h.length+1))],void 0==a.randAnim&&(a.randAnim="fade"));-1!=b.effect.indexOf(",")&&(h=b.effect.split(","),a.randAnim=h[Math.floor(Math.random()*h.length)],void 0==a.randAnim&&(a.randAnim="fade"));a.running=!0;if("sliceDown"==b.effect||"sliceDownRight"==b.effect||"sliceDownRight"==
a.randAnim||"sliceDownLeft"==b.effect||"sliceDownLeft"==a.randAnim){t(c,b,a);var d=0,g=0;h=e(".nivo-slice",c);if("sliceDownLeft"==b.effect||"sliceDownLeft"==a.randAnim)h=e(".nivo-slice",c)._reverse();h.each(function(){var a=e(this);a.css({top:"0px"});g==b.slices-1?setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},b.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+d):setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},b.animSpeed)},100+d);d+=50;g++})}else if("sliceUp"==
b.effect||"sliceUpRight"==b.effect||"sliceUpRight"==a.randAnim||"sliceUpLeft"==b.effect||"sliceUpLeft"==a.randAnim){t(c,b,a);g=d=0;h=e(".nivo-slice",c);if("sliceUpLeft"==b.effect||"sliceUpLeft"==a.randAnim)h=e(".nivo-slice",c)._reverse();h.each(function(){var a=e(this);a.css({bottom:"0px"});g==b.slices-1?setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},b.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+d):setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},b.animSpeed)},
100+d);d+=50;g++})}else if("sliceUpDown"==b.effect||"sliceUpDownRight"==b.effect||"sliceUpDown"==a.randAnim||"sliceUpDownLeft"==b.effect||"sliceUpDownLeft"==a.randAnim){t(c,b,a);var l=g=d=0;h=e(".nivo-slice",c);if("sliceUpDownLeft"==b.effect||"sliceUpDownLeft"==a.randAnim)h=e(".nivo-slice",c)._reverse();h.each(function(){var a=e(this);0==g?(a.css("top","0px"),g++):(a.css("bottom","0px"),g=0);l==b.slices-1?setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},b.animSpeed,"",function(){c.trigger("nivo:animFinished")})},
100+d):setTimeout(function(){a.animate({height:"100%",opacity:"1.0"},b.animSpeed)},100+d);d+=50;l++})}else if("fold"==b.effect||"fold"==a.randAnim)t(c,b,a),g=d=0,e(".nivo-slice",c).each(function(){var a=e(this),f=a.width();a.css({top:"0px",height:"100%",width:"0px"});g==b.slices-1?setTimeout(function(){a.animate({width:f,opacity:"1.0"},b.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+d):setTimeout(function(){a.animate({width:f,opacity:"1.0"},b.animSpeed)},100+d);d+=50;g++});else if("fade"==
b.effect||"fade"==a.randAnim){t(c,b,a);var k=e(".nivo-slice:first",c);k.css({height:"100%",width:c.width()+"px"});k.animate({opacity:"1.0"},2*b.animSpeed,"",function(){c.trigger("nivo:animFinished")})}else if("slideInRight"==b.effect||"slideInRight"==a.randAnim)t(c,b,a),k=e(".nivo-slice:first",c),k.css({height:"100%",width:"0px",opacity:"1"}),k.animate({width:c.width()+"px"},2*b.animSpeed,"",function(){c.trigger("nivo:animFinished")});else if("slideInLeft"==b.effect||"slideInLeft"==a.randAnim)t(c,
b,a),k=e(".nivo-slice:first",c),k.css({height:"100%",width:"0px",opacity:"1",left:"",right:"0px"}),k.animate({width:c.width()+"px"},2*b.animSpeed,"",function(){k.css({left:"0px",right:""});c.trigger("nivo:animFinished")});else if("boxRandom"==b.effect||"boxRandom"==a.randAnim){w(c,b,a);var p=b.boxCols*b.boxRows,d=g=0;h=u(e(".nivo-box",c));h.each(function(){var a=e(this);g==p-1?setTimeout(function(){a.animate({opacity:"1"},b.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+d):setTimeout(function(){a.animate({opacity:"1"},
b.animSpeed)},100+d);d+=20;g++})}else if("boxRain"==b.effect||"boxRain"==a.randAnim||"boxRainReverse"==b.effect||"boxRainReverse"==a.randAnim||"boxRainGrow"==b.effect||"boxRainGrow"==a.randAnim||"boxRainGrowReverse"==b.effect||"boxRainGrowReverse"==a.randAnim){w(c,b,a);var p=b.boxCols*b.boxRows,n=d=g=0,q=0,r=[];r[n]=[];h=e(".nivo-box",c);if("boxRainReverse"==b.effect||"boxRainReverse"==a.randAnim||"boxRainGrowReverse"==b.effect||"boxRainGrowReverse"==a.randAnim)h=e(".nivo-box",c)._reverse();h.each(function(){r[n][q]=
e(this);q++;q==b.boxCols&&(n++,q=0,r[n]=[])});for(h=0;h<2*b.boxCols;h++){f=h;for(var s=0;s<b.boxRows;s++)0<=f&&f<b.boxCols&&(function(d,f,g,h,m){var k=e(r[d][f]),l=k.width(),n=k.height();"boxRainGrow"!=b.effect&&"boxRainGrow"!=a.randAnim&&"boxRainGrowReverse"!=b.effect&&"boxRainGrowReverse"!=a.randAnim||k.width(0).height(0);h==m-1?setTimeout(function(){k.animate({opacity:"1",width:l,height:n},b.animSpeed/1.3,"",function(){c.trigger("nivo:animFinished")})},100+g):setTimeout(function(){k.animate({opacity:"1",
width:l,height:n},b.animSpeed/1.3)},100+g)}(s,f,d,g,p),g++),f--;d+=100}}},u=function(c){for(var d,b,e=c.length;e;d=parseInt(Math.random()*e),b=c[--e],c[e]=c[d],c[d]=b);return c},x=function(c){this.console&&"undefined"!=typeof console.log&&console.log(c)};this.stop=function(){e(n).data("nivo:vars").stop||(e(n).data("nivo:vars").stop=!0,x("Stop Slider"))};this.start=function(){e(n).data("nivo:vars").stop&&(e(n).data("nivo:vars").stop=!1,x("Start Slider"))};d.afterLoad.call(this);return this};e.fn.nivoSlider=
function(n){return this.each(function(v,d){var f=e(this);if(f.data("nivoslider"))return f.data("nivoslider");var g=new u(this,n);f.data("nivoslider",g)})};e.fn.nivoSlider.defaults={effect:"fade",slices:15,boxCols:8,boxRows:4,animSpeed:500,pauseTime:5E3,startSlide:0,directionNav:!0,directionNavHide:!1,controlNav:!0,controlNavThumbs:!1,controlNavThumbsFromRel:!1,controlNavThumbsSearch:".jpg",controlNavThumbsReplace:"_thumb.jpg",keyboardNav:!0,pauseOnHover:!1,manualAdvance:!1,captionOpacity:0,prevText:"Prev",
nextText:"Next",beforeChange:function(){},afterChange:function(){},slideshowEnd:function(){},lastSlide:function(){},afterLoad:function(){}};e.fn._reverse=[].reverse})(jQuery);