/*{"k":"1.7.2","created":"2014-04-09T08:43:15Z","version":"25277526","mac":"1:b798cf9fec6e55c436edc1ac86fde86c11d2e0373991bedc160a494c2e2239e3"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var j=!0,k=null,l=!1;function m(a){return function(){return this[a]}}var aa=this;function ba(a,b){var c=a.split("."),d=aa;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}}function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function n(a,b,c){n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return n.apply(k,arguments)}var ea=Date.now||function(){return+new Date};
function q(a,b){this.Y=a;this.O=b||a;this.D=this.O.document}q.prototype.createElement=function(a,b,c){a=this.D.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.D.createTextNode(c));return a};function r(a,b,c){a=a.D.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}function fa(a,b){function c(){a.D.body?b():setTimeout(c,0)}c()}
function s(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function t(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ga(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return j;return l}
function ha(a){var b=a.O.location.protocol;"about:"==b&&(b=a.Y.location.protocol);return"https:"==b?"https:":"http:"}
function ia(a,b,c){var d=a.D.getElementsByTagName("head")[0];if(d){var e=a.createElement("script",{src:b}),f=l;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=j,c&&c(k),e.onload=e.onreadystatechange=k,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e);window.setTimeout(function(){f||(f=j,c&&c(Error("Script load timeout")))},5E3)}}function u(a,b,c){this.Ma=a;this.aa=b;this.La=c}
ba("internalWebfont.BrowserInfo",u);u.prototype.Aa=m("Ma");u.prototype.hasWebFontSupport=u.prototype.Aa;u.prototype.Ba=m("aa");u.prototype.hasWebKitFallbackBug=u.prototype.Ba;u.prototype.Ca=m("La");u.prototype.hasWebKitMetricsBug=u.prototype.Ca;function v(a,b,c,d){this.e=a!=k?a:k;this.m=b!=k?b:k;this.C=c!=k?c:k;this.j=d!=k?d:k}var ja=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;
function w(a,b){return a.e>b.e||a.e===b.e&&a.m>b.m||a.e===b.e&&a.m===b.m&&a.C>b.C?1:a.e<b.e||a.e===b.e&&a.m<b.m||a.e===b.e&&a.m===b.m&&a.C<b.C?-1:0}function x(a,b){return 0===w(a,b)||1===w(a,b)}v.prototype.toString=function(){return[this.e,this.m||"",this.C||"",this.j||""].join("")};
function y(a){a=ja.exec(a);var b=k,c=k,d=k,e=k;a&&(a[1]!==k&&a[1]&&(b=parseInt(a[1],10)),a[2]!==k&&a[2]&&(c=parseInt(a[2],10)),a[3]!==k&&a[3]&&(d=parseInt(a[3],10)),a[4]!==k&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new v(b,c,d,e)}function z(a,b,c,d,e,f,g,h,p,K,D){this.P=a;this.n=b;this.Ka=c;this.u=d;this.z=e;this.qa=f;this.k=g;this.h=h;this.Ha=p;this.M=K;this.t=D}ba("internalWebfont.UserAgent",z);z.prototype.getName=m("P");z.prototype.getName=z.prototype.getName;
z.prototype.za=m("Ka");z.prototype.getVersion=z.prototype.za;z.prototype.va=m("u");z.prototype.getEngine=z.prototype.va;z.prototype.wa=m("qa");z.prototype.getEngineVersion=z.prototype.wa;z.prototype.xa=m("k");z.prototype.getPlatform=z.prototype.xa;z.prototype.ya=m("Ha");z.prototype.getPlatformVersion=z.prototype.ya;z.prototype.ua=m("M");z.prototype.getDocumentMode=z.prototype.ua;z.prototype.ta=m("t");z.prototype.getBrowserInfo=z.prototype.ta;function ma(a,b){this.c=a;this.L=b}
var na=new z("Unknown",new v,"Unknown","Unknown",new v,"Unknown","Unknown",new v,"Unknown",void 0,new u(l,l,l));
ma.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")||-1!=this.c.indexOf("Trident/")){a=A(this);var b=B(this),c=y(b),d=k,e=k,f=k,g=k,h=E(this.c,/Trident\/([\d\w\.]+)/,1),p=F(this.L),d=-1!=this.c.indexOf("MSIE")?E(this.c,/MSIE ([\d\w\.]+)/,1):E(this.c,/rv:([\d\w\.]+)/,1),e=y(d);""!=h?(f="Trident",g=y(h)):(f="Unknown",g=new v,h="Unknown");a=new z("MSIE",e,d,f,g,h,a,c,b,p,new u("Windows"==a&&6<=e.e||"Windows Phone"==a&&8<=c.e,l,l))}else if(-1!=this.c.indexOf("Opera"))a:if(a="Unknown",b=
E(this.c,/Presto\/([\d\w\.]+)/,1),c=y(b),d=B(this),e=y(d),f=F(this.L),c.e!==k?a="Presto":(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=E(this.c,/rv:([^\)]+)/,1),c=y(b)),-1!=this.c.indexOf("Opera Mini/"))g=E(this.c,/Opera Mini\/([\d\.]+)/,1),h=y(g),a=new z("OperaMini",h,g,a,c,b,A(this),e,d,f,new u(l,l,l));else{if(-1!=this.c.indexOf("Version/")&&(g=E(this.c,/Version\/([\d\.]+)/,1),h=y(g),h.e!==k)){a=new z("Opera",h,g,a,c,b,A(this),e,d,f,new u(10<=h.e,l,l));break a}g=E(this.c,/Opera[\/ ]([\d\.]+)/,1);
h=y(g);a=h.e!==k?new z("Opera",h,g,a,c,b,A(this),e,d,f,new u(10<=h.e,l,l)):new z("Opera",new v,"Unknown",a,c,b,A(this),e,d,f,new u(l,l,l))}else/OPR\/[\d.]+/.test(this.c)?a=oa(this):/AppleWeb(K|k)it/.test(this.c)?a=oa(this):-1!=this.c.indexOf("Gecko")?(a="Unknown",b=new v,c="Unknown",d=B(this),e=y(d),f=l,-1!=this.c.indexOf("Firefox")?(a="Firefox",c=E(this.c,/Firefox\/([\d\w\.]+)/,1),b=y(c),f=3<=b.e&&5<=b.m):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla"),g=E(this.c,/rv:([^\)]+)/,1),h=y(g),f||(f=1<h.e||
1==h.e&&9<h.m||1==h.e&&9==h.m&&2<=h.C||g.match(/1\.9\.1b[123]/)!=k||g.match(/1\.9\.1\.[\d\.]+/)!=k),a=new z(a,b,c,"Gecko",h,g,A(this),e,d,F(this.L),new u(f,l,l))):a=na;return a};function A(a){var b=E(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=E(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function B(a){var b=E(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=E(a.c,/Windows Phone( OS)? ([^;)]+)/,2))||(b=E(a.c,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=E(a.c,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=E(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function oa(a){var b=A(a),c=B(a),d=y(c),e=E(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),f=y(e),g="Unknown",h=new v,p="Unknown",K=l;/OPR\/[\d.]+/.test(a.c)?g="Opera":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?g="Chrome":/Silk\/\d/.test(a.c)?g="Silk":"BlackBerry"==b||"Android"==b?g="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?g="PhantomJS":-1!=a.c.indexOf("Safari")?g="Safari":-1!=a.c.indexOf("AdobeAIR")&&(g="AdobeAIR");"BuiltinBrowser"==g?p="Unknown":"Silk"==g?p=E(a.c,
/Silk\/([\d\._]+)/,1):"Chrome"==g?p=E(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?p=E(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==g?p=E(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==g?p=E(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==g&&(p=E(a.c,/PhantomJS\/([\d.]+)/,1));h=y(p);K="AdobeAIR"==g?2<h.e||2==h.e&&5<=h.m:"BlackBerry"==b?10<=d.e:"Android"==b?2<d.e||2==d.e&&1<d.m:526<=f.e||525<=f.e&&13<=f.m;return new z(g,h,p,"AppleWebKit",f,e,b,d,c,F(a.L),new u(K,536>f.e||536==f.e&&11>f.m,"iPhone"==
b||"iPad"==b||"iPod"==b||"Macintosh"==b))}function E(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function F(a){if(a.documentMode)return a.documentMode}function pa(a){this.Fa=a||"-"}pa.prototype.j=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Fa)};function qa(a,b,c){this.g=a;this.l=b;this.S=c;this.p="wf";this.o=new pa("-")}
function ra(a){t(a.l,a.o.j(a.p,"loading"));ga(a.l,a.o.j(a.p,"active"))||s(a.l,a.o.j(a.p,"inactive"));G(a,"inactive")}function G(a,b,c){if(a.S[b])if(c)a.S[b](c.getName(),I(c));else a.S[b]()}function J(a,b){this.P=a;this.ba=4;this.Q="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.Q=c[1],this.ba=parseInt(c[2],10))}J.prototype.getName=m("P");function I(a){return a.Q+a.ba}function L(a,b){this.g=a;this.I=b;this.w=this.g.createElement("span",{"aria-hidden":"true"},this.I)}
function sa(a,b){var c;c=[];for(var d=b.P.split(/,\s*/),e=0;e<d.length;e++){var f=d[e].replace(/['"]/g,"");-1==f.indexOf(" ")?c.push(f):c.push("'"+f+"'")}c=c.join(",");d="normal";e=b.ba+"00";"o"===b.Q?d="oblique":"i"===b.Q&&(d="italic");a.w.style.cssText="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+c+";"+("font-style:"+d+";font-weight:"+e+";")}
function ta(a){r(a.g,"body",a.w)}L.prototype.remove=function(){var a=this.w;a.parentNode&&a.parentNode.removeChild(a)};function ua(a,b,c,d,e,f,g,h){this.ca=a;this.Da=b;this.g=c;this.v=d;this.I=h||"BESbswy";this.t=e;this.J={};this.Z=f||5E3;this.ka=g||k;this.H=this.G=k;a=new L(this.g,this.I);ta(a);for(var p in M)M.hasOwnProperty(p)&&(sa(a,new J(M[p],I(this.v))),this.J[M[p]]=a.w.offsetWidth);a.remove()}var M={Ta:"serif",Sa:"sans-serif",Pa:"monospace"};
ua.prototype.start=function(){this.G=new L(this.g,this.I);ta(this.G);this.H=new L(this.g,this.I);ta(this.H);this.Ia=ea();sa(this.G,new J(this.v.getName()+",serif",I(this.v)));sa(this.H,new J(this.v.getName()+",sans-serif",I(this.v)));va(this)};function wa(a,b,c){for(var d in M)if(M.hasOwnProperty(d)&&b===a.J[M[d]]&&c===a.J[M[d]])return j;return l}
function va(a){var b=a.G.w.offsetWidth,c=a.H.w.offsetWidth;b===a.J.serif&&c===a.J["sans-serif"]||a.t.aa&&wa(a,b,c)?ea()-a.Ia>=a.Z?a.t.aa&&wa(a,b,c)&&(a.ka===k||a.ka.hasOwnProperty(a.v.getName()))?xa(a,a.ca):xa(a,a.Da):setTimeout(n(function(){va(this)},a),25):xa(a,a.ca)}function xa(a,b){a.G.remove();a.H.remove();b(a.v)}function N(a,b,c,d){this.g=b;this.A=c;this.V=0;this.na=this.ja=l;this.Z=d;this.t=a.t}
N.prototype.$=function(a,b,c,d){if(0===a.length&&d)ra(this.A);else{this.V+=a.length;d&&(this.ja=d);for(d=0;d<a.length;d++){var e=a[d],f=b[e.getName()],g=this.A,h=e;s(g.l,g.o.j(g.p,h.getName(),I(h).toString(),"loading"));G(g,"fontloading",h);(new ua(n(this.ra,this),n(this.sa,this),this.g,e,this.t,this.Z,c,f)).start()}}};
N.prototype.ra=function(a){var b=this.A;t(b.l,b.o.j(b.p,a.getName(),I(a).toString(),"loading"));t(b.l,b.o.j(b.p,a.getName(),I(a).toString(),"inactive"));s(b.l,b.o.j(b.p,a.getName(),I(a).toString(),"active"));G(b,"fontactive",a);this.na=j;ya(this)};N.prototype.sa=function(a){var b=this.A;t(b.l,b.o.j(b.p,a.getName(),I(a).toString(),"loading"));ga(b.l,b.o.j(b.p,a.getName(),I(a).toString(),"active"))||s(b.l,b.o.j(b.p,a.getName(),I(a).toString(),"inactive"));G(b,"fontinactive",a);ya(this)};
function ya(a){0==--a.V&&a.ja&&(a.na?(a=a.A,t(a.l,a.o.j(a.p,"loading")),t(a.l,a.o.j(a.p,"inactive")),s(a.l,a.o.j(a.p,"active")),G(a,"active")):ra(a.A))}function za(a){this.g=a}za.prototype.toString=function(){return encodeURIComponent(this.g.O.location.hostname||this.g.Y.location.hostname)};function Aa(a,b){this.q=a;this.s=b}
Aa.prototype.toString=function(){for(var a=[],b=0;b<this.s.length;b++)for(var c=this.s[b],d=c.B(),c=c.B(this.q),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=j;break a}f=l}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)c=a.slice(0>d-4?0:d-4,d),b.unshift(parseInt(c,2).toString(16));return b.join("")};function O(a){this.Ja=a}
O.prototype.j=function(a,b){var c=b||{},d=this.Ja.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function Ba(a,b,c,d){this.F=a;this.N=b;this.Wa=c;this.Xa=d;this.ha={};this.ga={}}Ba.prototype.B=function(a){return a?(this.ha[a]||this.N).slice(0):this.N.slice(0)};Ba.prototype.$=function(a,b,c){var d=[],e={};Ca(this,b,d,e);a(d,e,c)};
function Ca(a,b,c,d){c.push(a.F);d[a.F]=a.B(b);a=a.ga[b]||[];for(b=0;b<a.length;b++){for(var e=a[b],f=e.F,g=l,h=0;h<c.length;h++)c[h]==f&&(g=j);g||(c.push(f),d[f]=e.B())}}function Da(a,b){this.F=a;this.N=b}Da.prototype.B=m("N");function Ea(){this.pa=this.Na=this.K=this.W=this.Ea=j}function Q(a){return"Windows"===a.k}function R(a){return Q(a)&&0===w(a.h,new v(5,1))||Q(a)&&0===w(a.h,new v(5,2))||Q(a)&&0===w(a.h,new v(6,0))||Q(a)&&x(a.h,new v(6,1))}
function S(a){return"Macintosh"===a.k&&(x(a.h,new v(10,4))||a.h.e===k)}function Fa(a,b){return b.Ea&&("iPhone"===a.k||"iPod"===a.k)}function Ga(a,b){return Fa(a,b)&&x(a.h,new v(4,2))&&-1===w(a.h,new v(5))}function Ha(a,b){return b.W&&"iPad"===a.k&&x(a.h,new v(4,2))&&-1===w(a.h,new v(5))}function T(a,b){return b.K&&"Android"===a.k}function Ia(a,b){return T(a,b)&&x(a.h,new v(2,2))&&-1===w(a.h,new v(3,1))}function Ja(a,b){return T(a,b)&&x(a.h,new v(3,1))&&-1===w(a.h,new v(4,1))}
function U(a){return"Linux"===a.k||"Ubuntu"===a.k}function Ka(a){return"Gecko"===a.u&&0===w(a.z,new v(1,9,1))&&!/^b[1-3]$/.test(a.z.j||"")}function La(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u||"Unknown"===a.getName()&&"AppleWebKit"===a.u&&("iPhone"===a.k||"iPad"===a.k||"iPod"===a.k)}function Ma(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u&&x(a.z,new v(525,13))&&-1===w(a.z,new v(534,50))}function Na(a){return"Opera"===a.getName()&&x(a.n,new v(10,54))&&-1===w(a.n,new v(11,10))}
function Pa(a){return"BuiltinBrowser"===a.getName()}function Qa(a){this.ma=a}function Ra(a,b){return b}
var Sa={Qa:"a",Ra:"b",Va:"d",Ua:"f",Oa:"i"},Ta={a:function(a,b){return Ma(a)&&R(a)||Pa(a)&&(Ia(a,b)||T(a,b)&&x(a.h,new v(4,1)))||b.K&&"Silk"===a.getName()&&-1===w(a.n,new v(2))&&(Ia(a,b)||S)||b.K&&"Silk"===a.getName()&&x(a.n,new v(2))&&T(a,b)&&x(a.h,new v(4,1))||La(a)&&(Ha(a,b)||Ga(a,b))||Ka(a)&&(R(a)||U(a))||Na(a)&&(R(a)||U(a))||("Chrome"===a.getName()&&1===w(a.n,new v(4,0,249))&&-1===w(a.n,new v(6))||0===w(a.n,new v(4,0,249))&&(a.n.j===k||4<=a.n.j))&&(R(a)||U(a)||S(a))||"Chrome"===a.getName()&&
x(a.n,new v(6))&&(Ha(a,b)||Ga(a,b))||"AdobeAIR"===a.getName()&&x(a.n,new v(2,5))&&(Q(a)&&a.h.e===k||U(a))},b:function(a){return Ka(a)&&S(a)||Ma(a)&&S(a)||Na(a)&&S(a)||"AdobeAIR"===a.getName()&&x(a.n,new v(2,5))&&S(a)},d:function(a,b){return"Chrome"===a.getName()&&x(a.n,new v(6))&&(R(a)||U(a)||S(a)||T(a,b)||"CrOS"===a.k||b.W&&"iPad"===a.k&&x(a.h,new v(5))||Fa(a,b)&&x(a.h,new v(5)))||"Gecko"===a.u&&1===w(a.z,new v(1,9,1))&&(R(a)||U(a)||S(a)||T(a,b))||"Safari"===a.getName()&&("AppleWebKit"===a.u&&x(a.z,
new v(534,50)))&&(R(a)||S(a))||La(a)&&(b.W&&"iPad"===a.k&&x(a.h,new v(5))||Fa(a,b)&&x(a.h,new v(5)))||"Opera"===a.getName()&&x(a.n,new v(11,10))&&(R(a)||U(a)||S(a)||T(a,b))||"MSIE"===a.getName()&&9<=a.M&&(Q(a)&&x(a.h,new v(6,1))||Q(a)&&0===w(a.h,new v(6,0)))||"MSIE"===a.getName()&&b.Na&&"Windows Phone"===a.k&&x(a.h,new v(8))||Pa(a)&&b.pa&&"BlackBerry"===a.k&&x(a.h,new v(10))},f:function(a,b){return Pa(a)&&Ja(a,b)||b.K&&"Silk"===a.getName()&&x(a.n,new v(2))&&(Ja(a,b)||U(a))},i:function(a){return"MSIE"===
a.getName()&&(x(a.n,new v(6,0))&&(void 0===a.M||9>a.M))&&R(a)}};function Ua(a,b){var c=b||new Ea,d;for(d in Sa){var e=Sa[d];if(Ta[e](a,c))return e}return k}var Va={};
Va.i=new Qa(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;c.push(new Da(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++){var h=f[g];if(a[h]){d=d.concat(a[h]);break}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=j,a.push(f));c=[];for(d=0;d<b.length;d++){e=b[d];for(f=0;f<a.length;f++)g=a[f],g==e&&
c.push(g)}return c});var V={};V.a=V.b=V.d=function(){return[]};V.f=function(a){return[new za(a)]};V.i=function(a,b,c){return[new za(a),new Aa(b,c)]};function W(a){this.g=a;this.ea=this.c=this.q=k;this.s=[];this.T=[];this.oa=this.U=k}W.prototype.supportsConfiguredBrowser=function(){return!!this.q};
W.prototype.init=function(){if(0<this.T.length){for(var a=[],b=0;b<this.T.length;b++)a.push(this.T[b].Ya());var b=this.g,a=a.join(""),c=this.g.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));r(b,"head",c)}};
W.prototype.load=function(a,b,c){if(this.q){for(var d=Va[this.q]||new Qa(Ra),e=0;e<this.s.length;e++){for(var f=this.s[e],g=this.q,h=d,p=[],K=f.F.split(",")[0].replace(/"|'/g,""),D=f.B(),P=p,C=void 0,H=[],Oa={},ka=0;ka<D.length;ka++)C=D[ka],0<C.length&&!Oa[C]&&(Oa[C]=j,H.push(C));D=H;h=h.ma?h.ma(K,D,P):D;f.ha[g]=h;f.ga[g]=p}if(this.U){d=V[this.q](this.g,this.q,this.s);e=this.q;f=[];for(g=0;g<d.length;g++)f.push(d[g].toString());d={format:e,extras:f};c&&(d.contextPath=c);d=this.U.j("https:"===ha(this.g),
d);c=this.g;var d=c.createElement("link",{rel:"stylesheet",href:d}),X=l;d.onload=function(){X||(X=j)};d.onerror=function(){X||(X=j)};r(c,"head",d)}if(a){var la=this,cb=this.q;fa(this.g,function(){for(var c=0;c<la.s.length;c++)la.s[c].$(a,cb,b&&c==la.s.length-1)})}}};W.prototype.collectFontFamilies=function(a,b){if(this.q)for(var c=0;c<this.s.length;c++)Ca(this.s[c],this.q,a,b)};
W.prototype.performOptionalActions=function(){if(this.X){var a=this,b=this.c,c=this.g;fa(this.g,function(){var d=a.X;if(d.la){var e=window.__adobewebfontsappname__,e=e?e.toString().substr(0,20):"",d=d.la.j("https:"===ha(c),{host:encodeURIComponent(c.O.location.hostname||c.Y.location.hostname),app:encodeURIComponent(e),_:(+new Date).toString()}),f=new Image(1,1);f.src=d;f.onload=function(){f.onload=k}}d=a.X;d.da&&(d=d.da.j(b,c),r(c,"body",d))})}};
function Wa(a,b,c,d){this.Ga=a;this.fa=k;this.g=b;this.c=c;this.l=d;this.r=[]}Wa.prototype.R=function(a){this.r.push(a)};Wa.prototype.load=function(a,b){var c=a,d=b||{};if("string"==typeof c)c=[c];else if(!c||!c.length)d=c||{},c=[];if(c.length)for(var e=this,f=c.length,g=0;g<c.length;g++){var h=this.Ga.j("https:"===ha(this.g),{id:encodeURIComponent(c[g])});ia(this.g,h,function(){0==--f&&Xa(e,d)})}else Xa(this,d)};
function Xa(a,b){if(0!=a.r.length){a.fa=b.contextPath||k;for(var c=new qa(a.g,a.l,b),d=l,e=0;e<a.r.length;e++)a.r[e].init(),d=d||a.r[e].supportsConfiguredBrowser();if(d){s(c.l,c.o.j(c.p,"loading"));G(c,"loading");for(var f=new N(a.c,a.g,c,b.timeout),c=function(a,b,c){for(var d=[],e=0;e<a.length;e+=1){var P=a[e];if(b[P])for(var C=b[P],H=0;H<C.length;H+=1)d.push(new J(P,C[H]));else d.push(new J(P))}f.$(d,{},k,c)},d=0;d<a.r.length;d++)e=a.r[d],e.supportsConfiguredBrowser()&&(e.load(c,d==a.r.length-1,
a.fa),e.performOptionalActions(window))}else ra(c);a.r=[]}}function Ya(a){this.ia=a;this.r=[]}Ya.prototype.R=function(a){this.r.push(a)};
Ya.prototype.load=function(){var a=this.ia.__webfonttypekitmodule__;if(a)for(var b=0;b<this.r.length;b++){var c=this.r[b],d=a[c.oa];d&&d(function(a,b,d){a=[];b={};var h=(new ma(navigator.userAgent,document)).parse(),p=c;p.c=h;p.q=Ua(p.c,p.ea);c.supportsConfiguredBrowser()&&(c.init(),c.load(k),c.collectFontFamilies(a,b),c.performOptionalActions(window));d(c.supportsConfiguredBrowser(),a,b)})}};var Za=(new ma(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Y=new Wa(new O("//fonts.asos.com/{id}.js"),new q(window),Za,document.documentElement),Z=new Ya(window);window.Typekit.load=function(){Y.load.apply(Y,arguments)};window.Typekit.addKit=function(){Y.R.apply(Y,arguments)}}var $a=k,ab,$,$a=new O("//p.typekit.net/p.gif?a=615261&f=10881.10884&h={host}&ht=sh&k=lqd0ibp&s=1&_={_}");ab=new function(){var a=$a;this.da=k;this.la=a};$=new W(new q(window));$.oa="lqd0ibp";$.U=new O("//fonts.asos.com/k/lqd0ibp-{format}.css?3bb2a6e53c9684ffdc9a98f51d5b2a628100d31f37d8cd0435cad674eac82f607cef4d5c843b6ee28cc0bdc581b78284b30613a0dd23f5ccb6a8ea43940eed00dacb558ee36f61265030a6bb927c94a64774cb50b952a7351b0de6f9e3d75f82258f9f1eebe67837cc29a425f88c8dadc0acb226133035fcb76f8e533c83a2d1fc60f3d7687c6be4f1de238ae13e3d4950d7b30b16155d61823b03160995c492518da8d3285f1bf272ea5b172f1cf1b3a7e026a8a436c01e1a300c29cb9c42c79b09e14a86d98335f6885104ec876e3ac0eb2bebc5cbee22439e501d60af21de7bf045716531299de07b9b41e0");
$.X=ab;$.s.push(new Ba("futura-pt",["n4","n7"]));var bb;if(bb=Z)bb=!!Z.ia.__webfonttypekitmodule__;bb?(Z.R($),Z.load()):($.c=Za,$.q=Ua($.c,$.ea),window.Typekit.addKit($));
})(this,document);